/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormUtama.java
 *
 * Created on Jan 24, 2010, 5:59:22 PM
 */

package pkl49.view;

import javax.swing.JFrame;
import pkl49.component.PanelGradient;
import pkl49.component.PanelTransparan;
import pkl49.control.ControlMenu;
import pkl49.control.DataStatic;

/**
 *
 * @author tyaz_only
 */
public class FormUtama extends usu.widget.Form{

   

    /** Creates new form FormUtama */
    public FormUtama() {
        initComponents();
        Header.setGambar(true);
        panelKuesioner.setFormUtama(this);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
//        new PopUpHalamanSelection1(this);
        menu.setMain(this);
        panelKuesionerPodes.setFormUtama(this);
    }

//    public PanelKuesioner getPanelKuesioner1() {
//        return panelKuesioner1;
//    }

    public PanelGradient getPanelGradient1() {
        return panelGradient1;
    }

    public MainMenu getMenu() {
        return menu;
    }

    public PanelTransparan getPanelHome() {
        return panelHome;
    }

    public PanelTransparan getPanelInduk() {
        return panelInduk;
    }

    public PanelKuesioner getPanelKuesioner() {
        return panelKuesioner;
    }

    public PanelKuesionerPodes getPanelKuesionerPodes() {
        return panelKuesionerPodes;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new pkl49.component.PanelGradient();
        Header = new pkl49.component.PanelTransparan();
        WorkArea = new pkl49.component.PanelTransparan();
        panelInduk = new pkl49.component.PanelTransparan();
        menu = new pkl49.view.MainMenu();
        panelKuesioner = new pkl49.view.PanelKuesioner();
        panelKuesionerPodes = new pkl49.view.PanelKuesionerPodes();
        panelHome = new pkl49.component.PanelTransparan();
        buttonGlass1 = new pkl49.component.ButtonGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROGRAM ENTRY PKL 49"); // NOI18N

        panelGradient1.setFirstColor(new java.awt.Color(34, 59, 235));
        panelGradient1.setSecondColor(new java.awt.Color(51, 204, 255));

        Header.setBorder(null);
        Header.setColor(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        WorkArea.setBorder(null);
        WorkArea.setAlpha(20);
        WorkArea.setColor(new java.awt.Color(204, 204, 204));
        WorkArea.setLayout(new java.awt.BorderLayout());

        panelInduk.setBorder(null);
        panelInduk.setAlpha(5);
        panelInduk.setSabit(true);
        panelInduk.setLayout(new java.awt.CardLayout());
        panelInduk.add(menu, "Menu");
        panelInduk.add(panelKuesioner, "KuesionerRT");
        panelInduk.add(panelKuesionerPodes, "KuesionerPodes");

        panelHome.setBorder(null);
        panelHome.setAlpha(20);
        panelHome.setSabit(true);

        buttonGlass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/home_1.png"))); // NOI18N
        buttonGlass1.setToolTipText("Kembali ke menu utama"); // NOI18N
        buttonGlass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addComponent(buttonGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(926, Short.MAX_VALUE))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buttonGlass1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        panelInduk.add(panelHome, "card5");

        WorkArea.add(panelInduk, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(WorkArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
                    .addComponent(Header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WorkArea, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(panelGradient1, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1020)/2, (screenSize.height-698)/2, 1020, 698);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGlass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass1ActionPerformed
        ControlMenu.backToHome(this);
    }//GEN-LAST:event_buttonGlass1ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.PanelTransparan Header;
    private pkl49.component.PanelTransparan WorkArea;
    private pkl49.component.ButtonGlass buttonGlass1;
    private pkl49.view.MainMenu menu;
    private pkl49.component.PanelGradient panelGradient1;
    private pkl49.component.PanelTransparan panelHome;
    private pkl49.component.PanelTransparan panelInduk;
    private pkl49.view.PanelKuesioner panelKuesioner;
    private pkl49.view.PanelKuesionerPodes panelKuesionerPodes;
    // End of variables declaration//GEN-END:variables

   

}
