/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * hlm8.java
 *
 * Created on Jan 15, 2010, 9:57:57 AM
 */

package pkl49.view;

import java.util.ArrayList;
import java.util.List;
import pkl49.component.TextField;
import pkl49.validasi.ValidasiBlok8B;

/**
 *
 * @author Ade KeciL
 */
public class Halaman8 extends javax.swing.JPanel {

    private List<TextField> listBlok8B;
    private PanelKuesioner kuesioner;
    private ValidasiBlok8B validasiBlok8B;
    /** Creates new form hlm8 */
    public Halaman8() {
        initComponents();
        setList();
        for(int i=0;i<listBlok8B.size();i++){
            listBlok8B.get(i).setFocusTraversalKeysEnabled(false);
        }
    }

    
    public void setKuesioner(PanelKuesioner kuesioner) {
        this.kuesioner = kuesioner;
        validasiBlok8B = new ValidasiBlok8B(kuesioner, listBlok8B);
    }

    public List<TextField> getListBlok8B() {
        return listBlok8B;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scroolPane1 = new pkl49.component.ScroolPane();
        panelScroll = new pkl49.component.PanelTransparan();
        panelTabel = new pkl49.component.PanelTransparan();
        panelTransparan18 = new pkl49.component.PanelTransparan();
        label22 = new pkl49.component.Label();
        txtB8BR15 = new pkl49.component.TextField();
        panelTransparan19 = new pkl49.component.PanelTransparan();
        label23 = new pkl49.component.Label();
        txtB8BR16 = new pkl49.component.TextField();
        panelTransparan16 = new pkl49.component.PanelTransparan();
        label20 = new pkl49.component.Label();
        txtB8BR13 = new pkl49.component.TextField();
        panelTransparan17 = new pkl49.component.PanelTransparan();
        label21 = new pkl49.component.Label();
        txtB8BR14 = new pkl49.component.TextField();
        panelTransparan15 = new pkl49.component.PanelTransparan();
        label19 = new pkl49.component.Label();
        txtB8BR12 = new pkl49.component.TextField();
        panelTransparan14 = new pkl49.component.PanelTransparan();
        label18 = new pkl49.component.Label();
        txtB8BR11 = new pkl49.component.TextField();
        panelTransparan13 = new pkl49.component.PanelTransparan();
        label17 = new pkl49.component.Label();
        txtB8BR10 = new pkl49.component.TextField();
        panelTransparan12 = new pkl49.component.PanelTransparan();
        label16 = new pkl49.component.Label();
        txtB8BR9 = new pkl49.component.TextField();
        panelTransparan11 = new pkl49.component.PanelTransparan();
        label15 = new pkl49.component.Label();
        txtB8BR8 = new pkl49.component.TextField();
        panelTransparan10 = new pkl49.component.PanelTransparan();
        label14 = new pkl49.component.Label();
        txtB8BR7 = new pkl49.component.TextField();
        panelTransparan9 = new pkl49.component.PanelTransparan();
        label13 = new pkl49.component.Label();
        txtB8BR6 = new pkl49.component.TextField();
        panelTransparan8 = new pkl49.component.PanelTransparan();
        label12 = new pkl49.component.Label();
        txtB8BR5 = new pkl49.component.TextField();
        panelTransparan1 = new pkl49.component.PanelTransparan();
        label1 = new pkl49.component.Label();
        panelTransparan2 = new pkl49.component.PanelTransparan();
        label3 = new pkl49.component.Label();
        label4 = new pkl49.component.Label();
        txt8BPInformasi = new pkl49.component.TextField();
        txtB8BNoUrut = new pkl49.component.TextField();
        panelTransparan3 = new pkl49.component.PanelTransparan();
        label6 = new pkl49.component.Label();
        label7 = new pkl49.component.Label();
        label8 = new pkl49.component.Label();
        panelTransparan4 = new pkl49.component.PanelTransparan();
        label5 = new pkl49.component.Label();
        txtB8BR1 = new pkl49.component.TextField();
        panelTransparan5 = new pkl49.component.PanelTransparan();
        label9 = new pkl49.component.Label();
        txtB8BR2 = new pkl49.component.TextField();
        panelTransparan6 = new pkl49.component.PanelTransparan();
        label10 = new pkl49.component.Label();
        txtB8BR3 = new pkl49.component.TextField();
        panelTransparan7 = new pkl49.component.PanelTransparan();
        label11 = new pkl49.component.Label();
        txtB8BR4 = new pkl49.component.TextField();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panelScroll.setBorder(null);

        label22.setText("15. Saluran pembuangan air limbah tertutup lebih baik dibandingkan saluran pembuangan limbah terbuka");

        txtB8BR15.setMaxDigit('1');
        txtB8BR15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan18Layout = new javax.swing.GroupLayout(panelTransparan18);
        panelTransparan18.setLayout(panelTransparan18Layout);
        panelTransparan18Layout.setHorizontalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(txtB8BR15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan18Layout.setVerticalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label23.setText("16. Asap pabrik dan kendaraan bermotor menyebabkan polusi udara");

        txtB8BR16.setMaxDigit('1');
        txtB8BR16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan19Layout = new javax.swing.GroupLayout(panelTransparan19);
        panelTransparan19.setLayout(panelTransparan19Layout);
        panelTransparan19Layout.setHorizontalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                .addComponent(txtB8BR16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan19Layout.setVerticalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label20.setText("13. Jamban yang baik dan sehat adalah jamban yang berbentuk leher angsa");

        txtB8BR13.setMaxDigit('1');
        txtB8BR13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan16Layout = new javax.swing.GroupLayout(panelTransparan16);
        panelTransparan16.setLayout(panelTransparan16Layout);
        panelTransparan16Layout.setHorizontalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addComponent(txtB8BR13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan16Layout.setVerticalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label21.setText("14. Lantai tanah dapat menyebabkan risiko cacingan");

        txtB8BR14.setMaxDigit('1');
        txtB8BR14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan17Layout = new javax.swing.GroupLayout(panelTransparan17);
        panelTransparan17.setLayout(panelTransparan17Layout);
        panelTransparan17Layout.setHorizontalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 381, Short.MAX_VALUE)
                .addComponent(txtB8BR14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan17Layout.setVerticalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label19.setText("12. Jarak ideal antara septic tank dan sumber air minimal 10m");

        txtB8BR12.setMaxDigit('1');
        txtB8BR12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan15Layout = new javax.swing.GroupLayout(panelTransparan15);
        panelTransparan15.setLayout(panelTransparan15Layout);
        panelTransparan15Layout.setHorizontalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(txtB8BR12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan15Layout.setVerticalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label18.setText("11. Kebiasaan duduk terlalu lama dapat menyebabkan  risiko terkena ambeien");

        txtB8BR11.setMaxDigit('1');
        txtB8BR11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan14Layout = new javax.swing.GroupLayout(panelTransparan14);
        panelTransparan14.setLayout(panelTransparan14Layout);
        panelTransparan14Layout.setHorizontalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(txtB8BR11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan14Layout.setVerticalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label17.setText("10. Udara dingin dapat menyebabkan kambuhnya asma");

        txtB8BR10.setMaxDigit('1');
        txtB8BR10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan13Layout = new javax.swing.GroupLayout(panelTransparan13);
        panelTransparan13.setLayout(panelTransparan13Layout);
        panelTransparan13Layout.setHorizontalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                .addComponent(txtB8BR10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan13Layout.setVerticalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label16.setText("9. Susu yang mengandung kalsium baik untuk perkembangan tulang dan gigi");

        txtB8BR9.setMaxDigit('1');
        txtB8BR9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan12Layout = new javax.swing.GroupLayout(panelTransparan12);
        panelTransparan12.setLayout(panelTransparan12Layout);
        panelTransparan12Layout.setHorizontalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(txtB8BR9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan12Layout.setVerticalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label15.setText("8. Masyarakat bisa memperoleh pelayanan kesehatan gratis dengan menunjukkan KTP atau KK ke petugas pelayanan kesehatan");

        txtB8BR8.setMaxDigit('1');
        txtB8BR8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan11Layout = new javax.swing.GroupLayout(panelTransparan11);
        panelTransparan11.setLayout(panelTransparan11Layout);
        panelTransparan11Layout.setHorizontalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(txtB8BR8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan11Layout.setVerticalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label14.setText("7. Sarapan pagi dapat mempengaruhi produktivitas kerja");

        txtB8BR7.setMaxDigit('1');
        txtB8BR7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan10Layout = new javax.swing.GroupLayout(panelTransparan10);
        panelTransparan10.setLayout(panelTransparan10Layout);
        panelTransparan10Layout.setHorizontalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(txtB8BR7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan10Layout.setVerticalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label13.setText("6. Perokok pasif lebih beresiko terkena penyakit paru-paru dibandingkan perokok aktif");

        txtB8BR6.setMaxDigit('1');
        txtB8BR6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan9Layout = new javax.swing.GroupLayout(panelTransparan9);
        panelTransparan9.setLayout(panelTransparan9Layout);
        panelTransparan9Layout.setHorizontalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                .addComponent(txtB8BR6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan9Layout.setVerticalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label12.setText("5. Salah satu khasiat kunyit adalah untuk menurunkan demam");

        txtB8BR5.setMaxDigit('1');
        txtB8BR5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan8Layout = new javax.swing.GroupLayout(panelTransparan8);
        panelTransparan8.setLayout(panelTransparan8Layout);
        panelTransparan8Layout.setHorizontalGroup(
            panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 337, Short.MAX_VALUE)
                .addComponent(txtB8BR5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan8Layout.setVerticalGroup(
            panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTransparan1.setAlpha(75);
        panelTransparan1.setLayout(new java.awt.GridBagLayout());

        label1.setText("VIII.B. PENGETAHUAN KRT TENTANG KESEHATAN UNTUK ART UMUR \u2265  15 TAHUN KE ATAS ");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 94, 12, 90);
        panelTransparan1.add(label1, gridBagConstraints);

        label3.setText("Responden Pemberi Informasi");

        label4.setText("No. Urut ART");

        txt8BPInformasi.setCharType(2);
        txt8BPInformasi.setLength(25);
        txt8BPInformasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        txtB8BNoUrut.setLength(2);
        txtB8BNoUrut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan2Layout = new javax.swing.GroupLayout(panelTransparan2);
        panelTransparan2.setLayout(panelTransparan2Layout);
        panelTransparan2Layout.setHorizontalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt8BPInformasi, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txtB8BNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan2Layout.setVerticalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB8BNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8BPInformasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelTransparan3.setAlpha(60);

        label6.setText("No.");

        label7.setText("Rincian Pernyataan");

        label8.setText("Kode Jawaban");

        javax.swing.GroupLayout panelTransparan3Layout = new javax.swing.GroupLayout(panelTransparan3);
        panelTransparan3.setLayout(panelTransparan3Layout);
        panelTransparan3Layout.setHorizontalGroup(
            panelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 468, Short.MAX_VALUE)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan3Layout.setVerticalGroup(
            panelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label5.setText("1. Penyakit malaria disebarkan oleh nyamuk Anopheles");

        txtB8BR1.setMaxDigit('1');
        txtB8BR1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan4Layout = new javax.swing.GroupLayout(panelTransparan4);
        panelTransparan4.setLayout(panelTransparan4Layout);
        panelTransparan4Layout.setHorizontalGroup(
            panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(txtB8BR1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan4Layout.setVerticalGroup(
            panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label9.setText("2. Contoh diare dapat juga berupa disentri yang berupa tinja bercampur darah dan lendir");

        txtB8BR2.setMaxDigit('1');
        txtB8BR2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan5Layout = new javax.swing.GroupLayout(panelTransparan5);
        panelTransparan5.setLayout(panelTransparan5Layout);
        panelTransparan5Layout.setHorizontalGroup(
            panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addComponent(txtB8BR2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan5Layout.setVerticalGroup(
            panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label10.setText("3. Oralit dapat dibuat sendiri dengan cara melarutkan garam dan gula dengan air hangat ");

        txtB8BR3.setMaxDigit('1');
        txtB8BR3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan6Layout = new javax.swing.GroupLayout(panelTransparan6);
        panelTransparan6.setLayout(panelTransparan6Layout);
        panelTransparan6Layout.setHorizontalGroup(
            panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 206, Short.MAX_VALUE)
                .addComponent(txtB8BR3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan6Layout.setVerticalGroup(
            panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label11.setText("4. Temulawak dapat meningkatkan nafsu makan");

        txtB8BR4.setMaxDigit('1');
        txtB8BR4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan7Layout = new javax.swing.GroupLayout(panelTransparan7);
        panelTransparan7.setLayout(panelTransparan7Layout);
        panelTransparan7Layout.setHorizontalGroup(
            panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(txtB8BR4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan7Layout.setVerticalGroup(
            panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8BR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
            .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelScrollLayout = new javax.swing.GroupLayout(panelScroll);
        panelScroll.setLayout(panelScrollLayout);
        panelScrollLayout.setHorizontalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelScrollLayout.setVerticalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        scroolPane1.setViewportView(panelScroll);

        add(scroolPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void focusTxt(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusTxt
        panelTabel.scrollRectToVisible(evt.getComponent().getParent().getBounds(null));
    }//GEN-LAST:event_focusTxt


    protected void setList(){
        listBlok8B = new ArrayList<TextField>();
        listBlok8B.add(txt8BPInformasi);
        listBlok8B.add(txtB8BNoUrut);
        listBlok8B.add(txtB8BR1);
        listBlok8B.add(txtB8BR2);
        listBlok8B.add(txtB8BR3);
        listBlok8B.add(txtB8BR4);
        listBlok8B.add(txtB8BR5);
        listBlok8B.add(txtB8BR6);
        listBlok8B.add(txtB8BR7);
        listBlok8B.add(txtB8BR8);
        listBlok8B.add(txtB8BR9);
        listBlok8B.add(txtB8BR10);
        listBlok8B.add(txtB8BR11);
        listBlok8B.add(txtB8BR12);
        listBlok8B.add(txtB8BR13);
        listBlok8B.add(txtB8BR14);
        listBlok8B.add(txtB8BR15);
        listBlok8B.add(txtB8BR16);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.Label label1;
    private pkl49.component.Label label10;
    private pkl49.component.Label label11;
    private pkl49.component.Label label12;
    private pkl49.component.Label label13;
    private pkl49.component.Label label14;
    private pkl49.component.Label label15;
    private pkl49.component.Label label16;
    private pkl49.component.Label label17;
    private pkl49.component.Label label18;
    private pkl49.component.Label label19;
    private pkl49.component.Label label20;
    private pkl49.component.Label label21;
    private pkl49.component.Label label22;
    private pkl49.component.Label label23;
    private pkl49.component.Label label3;
    private pkl49.component.Label label4;
    private pkl49.component.Label label5;
    private pkl49.component.Label label6;
    private pkl49.component.Label label7;
    private pkl49.component.Label label8;
    private pkl49.component.Label label9;
    private pkl49.component.PanelTransparan panelScroll;
    private pkl49.component.PanelTransparan panelTabel;
    private pkl49.component.PanelTransparan panelTransparan1;
    private pkl49.component.PanelTransparan panelTransparan10;
    private pkl49.component.PanelTransparan panelTransparan11;
    private pkl49.component.PanelTransparan panelTransparan12;
    private pkl49.component.PanelTransparan panelTransparan13;
    private pkl49.component.PanelTransparan panelTransparan14;
    private pkl49.component.PanelTransparan panelTransparan15;
    private pkl49.component.PanelTransparan panelTransparan16;
    private pkl49.component.PanelTransparan panelTransparan17;
    private pkl49.component.PanelTransparan panelTransparan18;
    private pkl49.component.PanelTransparan panelTransparan19;
    private pkl49.component.PanelTransparan panelTransparan2;
    private pkl49.component.PanelTransparan panelTransparan3;
    private pkl49.component.PanelTransparan panelTransparan4;
    private pkl49.component.PanelTransparan panelTransparan5;
    private pkl49.component.PanelTransparan panelTransparan6;
    private pkl49.component.PanelTransparan panelTransparan7;
    private pkl49.component.PanelTransparan panelTransparan8;
    private pkl49.component.PanelTransparan panelTransparan9;
    private pkl49.component.ScroolPane scroolPane1;
    private pkl49.component.TextField txt8BPInformasi;
    private pkl49.component.TextField txtB8BNoUrut;
    private pkl49.component.TextField txtB8BR1;
    private pkl49.component.TextField txtB8BR10;
    private pkl49.component.TextField txtB8BR11;
    private pkl49.component.TextField txtB8BR12;
    private pkl49.component.TextField txtB8BR13;
    private pkl49.component.TextField txtB8BR14;
    private pkl49.component.TextField txtB8BR15;
    private pkl49.component.TextField txtB8BR16;
    private pkl49.component.TextField txtB8BR2;
    private pkl49.component.TextField txtB8BR3;
    private pkl49.component.TextField txtB8BR4;
    private pkl49.component.TextField txtB8BR5;
    private pkl49.component.TextField txtB8BR6;
    private pkl49.component.TextField txtB8BR7;
    private pkl49.component.TextField txtB8BR8;
    private pkl49.component.TextField txtB8BR9;
    // End of variables declaration//GEN-END:variables

}
