/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Halaman9.java
 *
 * Created on 18 Jan 10, 7:07:29
 */

package pkl49.view;

import java.util.ArrayList;
import java.util.List;
import pkl49.component.TextField;
import pkl49.validasi.ValidasiBlok8C;

/**
 *
 * @author Ken
 */
public class Halaman9 extends javax.swing.JPanel {

    private List<TextField> listBlok8C;
    private ValidasiBlok8C val;
    private PanelKuesioner kuesioner;
    /** Creates new form Halaman9 */
    public Halaman9() {
        initComponents();
        setListTxt();
        for(int i=0;i<listBlok8C.size();i++){
            listBlok8C.get(i).setFocusTraversalKeysEnabled(false);
        }
    }

    public List<TextField> getListBlok8C() {
        return listBlok8C;
    }

    public void setKuesioner(PanelKuesioner kuesioner) {
        this.kuesioner = kuesioner;
        val = new ValidasiBlok8C(this.kuesioner, listBlok8C);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scroolPane1 = new pkl49.component.ScroolPane();
        panelScroll = new pkl49.component.PanelTransparan();
        panelTransparan2 = new pkl49.component.PanelTransparan();
        panelTransparan3 = new pkl49.component.PanelTransparan();
        label1 = new pkl49.component.Label();
        label2 = new pkl49.component.Label();
        panelTransparan4 = new pkl49.component.PanelTransparan();
        label3 = new pkl49.component.Label();
        label4 = new pkl49.component.Label();
        txt8CPInformasi = new pkl49.component.TextField();
        txtB8CNoART = new pkl49.component.TextField();
        txtB8CNoBayi = new pkl49.component.TextField();
        label9 = new pkl49.component.Label();
        txtB8CNamaBayi = new pkl49.component.TextField();
        label11 = new pkl49.component.Label();
        panelTransparan5 = new pkl49.component.PanelTransparan();
        label6 = new pkl49.component.Label();
        label7 = new pkl49.component.Label();
        label8 = new pkl49.component.Label();
        panelTransparan6 = new pkl49.component.PanelTransparan();
        label5 = new pkl49.component.Label();
        txtB8CR1 = new pkl49.component.TextField();
        label10 = new pkl49.component.Label();
        panelTransparan11 = new pkl49.component.PanelTransparan();
        label17 = new pkl49.component.Label();
        txtB8CR2 = new pkl49.component.TextField();
        panelTransparan12 = new pkl49.component.PanelTransparan();
        label18 = new pkl49.component.Label();
        txtB8CR3 = new pkl49.component.TextField();
        panelTransparan13 = new pkl49.component.PanelTransparan();
        label19 = new pkl49.component.Label();
        txtB8CR4 = new pkl49.component.TextField();
        panelTransparan14 = new pkl49.component.PanelTransparan();
        label20 = new pkl49.component.Label();
        txtB8CR5 = new pkl49.component.TextField();
        panelTransparan9 = new pkl49.component.PanelTransparan();
        label13 = new pkl49.component.Label();
        txtB8CR6 = new pkl49.component.TextField();
        panelTransparan10 = new pkl49.component.PanelTransparan();
        label14 = new pkl49.component.Label();
        txtB8CR7 = new pkl49.component.TextField();
        panelTransparan15 = new pkl49.component.PanelTransparan();
        label15 = new pkl49.component.Label();
        txtB8CR8 = new pkl49.component.TextField();
        panelTransparan16 = new pkl49.component.PanelTransparan();
        label16 = new pkl49.component.Label();
        txtB8CR9 = new pkl49.component.TextField();
        panelTransparan17 = new pkl49.component.PanelTransparan();
        label21 = new pkl49.component.Label();
        txtB8CR10 = new pkl49.component.TextField();
        panelTransparan18 = new pkl49.component.PanelTransparan();
        label22 = new pkl49.component.Label();
        txtB8CR11 = new pkl49.component.TextField();
        panelTransparan19 = new pkl49.component.PanelTransparan();
        label23 = new pkl49.component.Label();
        txtB8CR12 = new pkl49.component.TextField();
        label40 = new pkl49.component.Label();
        panelTransparan20 = new pkl49.component.PanelTransparan();
        label24 = new pkl49.component.Label();
        txtB8CR13 = new pkl49.component.TextField();
        panelTransparan21 = new pkl49.component.PanelTransparan();
        label25 = new pkl49.component.Label();
        txtB8CR14 = new pkl49.component.TextField();
        label41 = new pkl49.component.Label();
        panelTransparan22 = new pkl49.component.PanelTransparan();
        label26 = new pkl49.component.Label();
        txtB8CR15 = new pkl49.component.TextField();
        label42 = new pkl49.component.Label();
        panelTransparan23 = new pkl49.component.PanelTransparan();
        label27 = new pkl49.component.Label();
        txtB8CR16 = new pkl49.component.TextField();
        panelTransparan24 = new pkl49.component.PanelTransparan();
        label28 = new pkl49.component.Label();
        txtB8CR17 = new pkl49.component.TextField();
        label43 = new pkl49.component.Label();
        panelTransparan25 = new pkl49.component.PanelTransparan();
        label29 = new pkl49.component.Label();
        txtB8CR18 = new pkl49.component.TextField();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panelTransparan3.setLayout(new java.awt.GridBagLayout());

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("VIII.C. PENGETAHUAN IBU/WALI TENTANG KESEHATAN");
        label1.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 168, 0, 169);
        panelTransparan3.add(label1, gridBagConstraints);

        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("[Untuk Ibu/wali yang memiliki bayi berumur 0-11 bulan]");
        label2.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 168, 17, 169);
        panelTransparan3.add(label2, gridBagConstraints);

        label3.setText("Responden Pemberi Informasi:");

        label4.setText("No. Urut ART");

        txt8CPInformasi.setEditable(false);
        txt8CPInformasi.setCharType(2);
        txt8CPInformasi.setLength(30);
        txt8CPInformasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        txtB8CNoART.setLength(2);
        txtB8CNoART.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        txtB8CNoBayi.setLength(2);
        txtB8CNoBayi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtB8CNoBayifocusTxt(evt);
            }
        });

        label9.setText("No. Urut bayi");

        txtB8CNamaBayi.setEditable(false);
        txtB8CNamaBayi.setCharType(2);
        txtB8CNamaBayi.setLength(30);
        txtB8CNamaBayi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtB8CNamaBayifocusTxt(evt);
            }
        });

        label11.setText("Nam Bayi:");

        javax.swing.GroupLayout panelTransparan4Layout = new javax.swing.GroupLayout(panelTransparan4);
        panelTransparan4.setLayout(panelTransparan4Layout);
        panelTransparan4Layout.setHorizontalGroup(
            panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtB8CNamaBayi, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(txt8CPInformasi, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTransparan4Layout.createSequentialGroup()
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(txtB8CNoART, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan4Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtB8CNoBayi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTransparan4Layout.setVerticalGroup(
            panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB8CNoART, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt8CPInformasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtB8CNoBayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtB8CNamaBayi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(panelTransparan4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        label6.setText("No.");

        label7.setText("Rincian Pernyataan");

        label8.setText("Kode Jawaban");

        javax.swing.GroupLayout panelTransparan5Layout = new javax.swing.GroupLayout(panelTransparan5);
        panelTransparan5.setLayout(panelTransparan5Layout);
        panelTransparan5Layout.setHorizontalGroup(
            panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(270, 270, 270)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan5Layout.setVerticalGroup(
            panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label5.setText("1. Ibu hamil yang mengkonsumsi vitamin A secara berlebihan selama beberapa bulan dapat beresiko");

        txtB8CR1.setMaxDigit('1');
        txtB8CR1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        label10.setText("melahirkan bayi yang cacat jaringan syaraf");

        javax.swing.GroupLayout panelTransparan6Layout = new javax.swing.GroupLayout(panelTransparan6);
        panelTransparan6.setLayout(panelTransparan6Layout);
        panelTransparan6Layout.setHorizontalGroup(
            panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan6Layout.createSequentialGroup()
                .addGroup(panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(txtB8CR1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTransparan6Layout.setVerticalGroup(
            panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan6Layout.createSequentialGroup()
                        .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtB8CR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label17.setText("2. Kekurangan kalsium pada ibu hamil dapat menyebabkan osteoporosis (tulang keropos)");

        txtB8CR2.setMaxDigit('1');
        txtB8CR2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan11Layout = new javax.swing.GroupLayout(panelTransparan11);
        panelTransparan11.setLayout(panelTransparan11Layout);
        panelTransparan11Layout.setHorizontalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 191, Short.MAX_VALUE)
                .addComponent(txtB8CR2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan11Layout.setVerticalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label18.setText("3. Zat besi diperlukan oleh ibu hamil agar terhidar dari anemia");

        txtB8CR3.setMaxDigit('1');
        txtB8CR3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan12Layout = new javax.swing.GroupLayout(panelTransparan12);
        panelTransparan12.setLayout(panelTransparan12Layout);
        panelTransparan12Layout.setHorizontalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(txtB8CR3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan12Layout.setVerticalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label19.setText("4. Memperbanyak sujud (nungging) sangat dianjurkan untuk ibu hamil dengan kondisi janin sungsang");

        txtB8CR4.setMaxDigit('1');
        txtB8CR4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan13Layout = new javax.swing.GroupLayout(panelTransparan13);
        panelTransparan13.setLayout(panelTransparan13Layout);
        panelTransparan13Layout.setHorizontalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(txtB8CR4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan13Layout.setVerticalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label20.setText("5. Makanan berkadar garam tinggi berpotensi meningkatkan tekanan darah dan protein pada urin");

        txtB8CR5.setMaxDigit('1');
        txtB8CR5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan14Layout = new javax.swing.GroupLayout(panelTransparan14);
        panelTransparan14.setLayout(panelTransparan14Layout);
        panelTransparan14Layout.setHorizontalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(txtB8CR5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan14Layout.setVerticalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label13.setText("6. Kalsium dibutuhkan oleh ibu hamil salah satu untuk pembentukan tulang janin");

        txtB8CR6.setMaxDigit('1');
        txtB8CR6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan9Layout = new javax.swing.GroupLayout(panelTransparan9);
        panelTransparan9.setLayout(panelTransparan9Layout);
        panelTransparan9Layout.setHorizontalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(txtB8CR6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan9Layout.setVerticalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label14.setText("7. Ibu hamil dengan berat badan berlebih tidak dianjurkan untuk melakukan diet");

        txtB8CR7.setMaxDigit('1');
        txtB8CR7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan10Layout = new javax.swing.GroupLayout(panelTransparan10);
        panelTransparan10.setLayout(panelTransparan10Layout);
        panelTransparan10Layout.setHorizontalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(txtB8CR7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan10Layout.setVerticalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label15.setText("8. Colostrum/ASI yang pertama kali baik diberikan kepada bayi");

        txtB8CR8.setMaxDigit('1');
        txtB8CR8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan15Layout = new javax.swing.GroupLayout(panelTransparan15);
        panelTransparan15.setLayout(panelTransparan15Layout);
        panelTransparan15Layout.setHorizontalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 317, Short.MAX_VALUE)
                .addComponent(txtB8CR8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan15Layout.setVerticalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label16.setText("9. ASI eksklusif diberikan kepada bayi hingga usia 6 bulan");

        txtB8CR9.setMaxDigit('1');
        txtB8CR9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan16Layout = new javax.swing.GroupLayout(panelTransparan16);
        panelTransparan16.setLayout(panelTransparan16Layout);
        panelTransparan16Layout.setHorizontalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 341, Short.MAX_VALUE)
                .addComponent(txtB8CR9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan16Layout.setVerticalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label21.setText("10. Diare dapat disebabkan karena ketidakcocokan terhadap susu formula");

        txtB8CR10.setMaxDigit('1');
        txtB8CR10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan17Layout = new javax.swing.GroupLayout(panelTransparan17);
        panelTransparan17.setLayout(panelTransparan17Layout);
        panelTransparan17Layout.setHorizontalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 261, Short.MAX_VALUE)
                .addComponent(txtB8CR10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan17Layout.setVerticalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label22.setText("11. Bayi yang mengkonsumsi makanan padat terlalu dini dapat berisiko kegemukan yang berbahaya bagi jantung");

        txtB8CR11.setMaxDigit('1');
        txtB8CR11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan18Layout = new javax.swing.GroupLayout(panelTransparan18);
        panelTransparan18.setLayout(panelTransparan18Layout);
        panelTransparan18Layout.setHorizontalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(txtB8CR11, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan18Layout.setVerticalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label23.setText("12. Campuran bayam, wortel, kuning telur, dan daging merupakan makanan pendamping yang baik untuk");

        txtB8CR12.setMaxDigit('1');
        txtB8CR12.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        label40.setText("bayi usia 6 bulan ke atas ");

        javax.swing.GroupLayout panelTransparan19Layout = new javax.swing.GroupLayout(panelTransparan19);
        panelTransparan19.setLayout(panelTransparan19Layout);
        panelTransparan19Layout.setHorizontalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan19Layout.createSequentialGroup()
                .addGroup(panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan19Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(txtB8CR12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan19Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTransparan19Layout.setVerticalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan19Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan19Layout.createSequentialGroup()
                        .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtB8CR12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label24.setText("13. Imunisasi BCG diberikan pada saat bayi berumur kurang dari 1 bulan");

        txtB8CR13.setMaxDigit('1');
        txtB8CR13.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan20Layout = new javax.swing.GroupLayout(panelTransparan20);
        panelTransparan20.setLayout(panelTransparan20Layout);
        panelTransparan20Layout.setHorizontalGroup(
            panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(txtB8CR13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan20Layout.setVerticalGroup(
            panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label25.setText("14. Setelah 4-6 minggu ditempat bekas suntikan imunisasi BCG akan timbul bisul yang akan pecah, bentuknya ");

        txtB8CR14.setMaxDigit('1');
        txtB8CR14.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        label41.setText("seperti koreng, reaksi ini merupakan hal yang normal");

        javax.swing.GroupLayout panelTransparan21Layout = new javax.swing.GroupLayout(panelTransparan21);
        panelTransparan21.setLayout(panelTransparan21Layout);
        panelTransparan21Layout.setHorizontalGroup(
            panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan21Layout.createSequentialGroup()
                .addGroup(panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan21Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(txtB8CR14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan21Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTransparan21Layout.setVerticalGroup(
            panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan21Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan21Layout.createSequentialGroup()
                        .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtB8CR14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label26.setText("15. Bayi yang dalam jangka waktu 3 bulan terakhir baru mendapat transfusi darah tidak dianjurkan melakukan");

        txtB8CR15.setMaxDigit('1');
        txtB8CR15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        label42.setText("imunisasi");

        javax.swing.GroupLayout panelTransparan22Layout = new javax.swing.GroupLayout(panelTransparan22);
        panelTransparan22.setLayout(panelTransparan22Layout);
        panelTransparan22Layout.setHorizontalGroup(
            panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan22Layout.createSequentialGroup()
                .addGroup(panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(txtB8CR15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan22Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(label42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTransparan22Layout.setVerticalGroup(
            panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan22Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan22Layout.createSequentialGroup()
                        .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtB8CR15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label27.setText("16. Ketika bayi mengalami diare sebaiknya perbanyak pemberian air minum");

        txtB8CR16.setMaxDigit('1');
        txtB8CR16.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan23Layout = new javax.swing.GroupLayout(panelTransparan23);
        panelTransparan23.setLayout(panelTransparan23Layout);
        panelTransparan23Layout.setHorizontalGroup(
            panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(txtB8CR16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan23Layout.setVerticalGroup(
            panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan23Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label28.setText("17. Salah satu perawatan bayi yang terkena penyakit kuning yang terlalu parah adalah dengan pemberian");

        txtB8CR17.setMaxDigit('1');
        txtB8CR17.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        label43.setText("cukup minum");

        javax.swing.GroupLayout panelTransparan24Layout = new javax.swing.GroupLayout(panelTransparan24);
        panelTransparan24.setLayout(panelTransparan24Layout);
        panelTransparan24Layout.setHorizontalGroup(
            panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan24Layout.createSequentialGroup()
                .addGroup(panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan24Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(txtB8CR17, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan24Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelTransparan24Layout.setVerticalGroup(
            panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan24Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan24Layout.createSequentialGroup()
                        .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtB8CR17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label29.setText("18. Aspirin tidak boleh diberikan kepada bayi");

        txtB8CR18.setMaxDigit('1');
        txtB8CR18.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan25Layout = new javax.swing.GroupLayout(panelTransparan25);
        panelTransparan25.setLayout(panelTransparan25Layout);
        panelTransparan25Layout.setHorizontalGroup(
            panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addComponent(txtB8CR18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan25Layout.setVerticalGroup(
            panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtB8CR18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTransparan2Layout = new javax.swing.GroupLayout(panelTransparan2);
        panelTransparan2.setLayout(panelTransparan2Layout);
        panelTransparan2Layout.setHorizontalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
            .addComponent(panelTransparan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTransparan2Layout.setVerticalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan2Layout.createSequentialGroup()
                .addComponent(panelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelScrollLayout = new javax.swing.GroupLayout(panelScroll);
        panelScroll.setLayout(panelScrollLayout);
        panelScrollLayout.setHorizontalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelScrollLayout.setVerticalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        scroolPane1.setViewportView(panelScroll);

        add(scroolPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void focusTxt(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusTxt
        panelScroll.scrollRectToVisible(evt.getComponent().getParent().getBounds(null));
    }


    public TextField getTxtB8CR9() {
        return txtB8CR8;
    }//GEN-LAST:event_focusTxt

    private void txtB8CNoBayifocusTxt(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtB8CNoBayifocusTxt
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB8CNoBayifocusTxt

    private void txtB8CNamaBayifocusTxt(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtB8CNamaBayifocusTxt
        // TODO add your handling code here:
    }//GEN-LAST:event_txtB8CNamaBayifocusTxt

    /**
     *
     */
    private void setListTxt(){
        listBlok8C = new ArrayList<TextField>();
        listBlok8C.add(txt8CPInformasi);
        listBlok8C.add(txtB8CNamaBayi);
        listBlok8C.add(txtB8CNoART);
        listBlok8C.add(txtB8CNoBayi);
        listBlok8C.add(txtB8CR1);
        listBlok8C.add(txtB8CR2);
        listBlok8C.add(txtB8CR3);
        listBlok8C.add(txtB8CR4);
        listBlok8C.add(txtB8CR5);
        listBlok8C.add(txtB8CR6);
        listBlok8C.add(txtB8CR7);
        listBlok8C.add(txtB8CR8);
        listBlok8C.add(txtB8CR9);
        listBlok8C.add(txtB8CR10);
        listBlok8C.add(txtB8CR11);
        listBlok8C.add(txtB8CR12);
        listBlok8C.add(txtB8CR13);
        listBlok8C.add(txtB8CR14);
        listBlok8C.add(txtB8CR15);
        listBlok8C.add(txtB8CR16);
        listBlok8C.add(txtB8CR17);
        listBlok8C.add(txtB8CR18);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.Label label1;
    private pkl49.component.Label label10;
    private pkl49.component.Label label11;
    private pkl49.component.Label label13;
    private pkl49.component.Label label14;
    private pkl49.component.Label label15;
    private pkl49.component.Label label16;
    private pkl49.component.Label label17;
    private pkl49.component.Label label18;
    private pkl49.component.Label label19;
    private pkl49.component.Label label2;
    private pkl49.component.Label label20;
    private pkl49.component.Label label21;
    private pkl49.component.Label label22;
    private pkl49.component.Label label23;
    private pkl49.component.Label label24;
    private pkl49.component.Label label25;
    private pkl49.component.Label label26;
    private pkl49.component.Label label27;
    private pkl49.component.Label label28;
    private pkl49.component.Label label29;
    private pkl49.component.Label label3;
    private pkl49.component.Label label4;
    private pkl49.component.Label label40;
    private pkl49.component.Label label41;
    private pkl49.component.Label label42;
    private pkl49.component.Label label43;
    private pkl49.component.Label label5;
    private pkl49.component.Label label6;
    private pkl49.component.Label label7;
    private pkl49.component.Label label8;
    private pkl49.component.Label label9;
    private pkl49.component.PanelTransparan panelScroll;
    private pkl49.component.PanelTransparan panelTransparan10;
    private pkl49.component.PanelTransparan panelTransparan11;
    private pkl49.component.PanelTransparan panelTransparan12;
    private pkl49.component.PanelTransparan panelTransparan13;
    private pkl49.component.PanelTransparan panelTransparan14;
    private pkl49.component.PanelTransparan panelTransparan15;
    private pkl49.component.PanelTransparan panelTransparan16;
    private pkl49.component.PanelTransparan panelTransparan17;
    private pkl49.component.PanelTransparan panelTransparan18;
    private pkl49.component.PanelTransparan panelTransparan19;
    private pkl49.component.PanelTransparan panelTransparan2;
    private pkl49.component.PanelTransparan panelTransparan20;
    private pkl49.component.PanelTransparan panelTransparan21;
    private pkl49.component.PanelTransparan panelTransparan22;
    private pkl49.component.PanelTransparan panelTransparan23;
    private pkl49.component.PanelTransparan panelTransparan24;
    private pkl49.component.PanelTransparan panelTransparan25;
    private pkl49.component.PanelTransparan panelTransparan3;
    private pkl49.component.PanelTransparan panelTransparan4;
    private pkl49.component.PanelTransparan panelTransparan5;
    private pkl49.component.PanelTransparan panelTransparan6;
    private pkl49.component.PanelTransparan panelTransparan9;
    private pkl49.component.ScroolPane scroolPane1;
    private pkl49.component.TextField txt8CPInformasi;
    private pkl49.component.TextField txtB8CNamaBayi;
    private pkl49.component.TextField txtB8CNoART;
    private pkl49.component.TextField txtB8CNoBayi;
    private pkl49.component.TextField txtB8CR1;
    private pkl49.component.TextField txtB8CR10;
    private pkl49.component.TextField txtB8CR11;
    private pkl49.component.TextField txtB8CR12;
    private pkl49.component.TextField txtB8CR13;
    private pkl49.component.TextField txtB8CR14;
    private pkl49.component.TextField txtB8CR15;
    private pkl49.component.TextField txtB8CR16;
    private pkl49.component.TextField txtB8CR17;
    private pkl49.component.TextField txtB8CR18;
    private pkl49.component.TextField txtB8CR2;
    private pkl49.component.TextField txtB8CR3;
    private pkl49.component.TextField txtB8CR4;
    private pkl49.component.TextField txtB8CR5;
    private pkl49.component.TextField txtB8CR6;
    private pkl49.component.TextField txtB8CR7;
    private pkl49.component.TextField txtB8CR8;
    private pkl49.component.TextField txtB8CR9;
    // End of variables declaration//GEN-END:variables

}
