/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * Hal6.java
 *
 * Created on Jan 19, 2010, 10:40:59 AM
 */

package pkl49.view;

import java.util.ArrayList;
import java.util.List;
import pkl49.component.TextField;

/**
 *
 * @author tyaz_only
 */
public class Halaman5 extends javax.swing.JPanel {

    private List<TextField> listBlok7A;

    /** Creates new form Hal6 */
    public Halaman5() {
        initComponents();
        setListText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scroolPane1 = new pkl49.component.ScroolPane();
        panelScroll = new pkl49.component.PanelTransparan();
        panelTransparan1 = new pkl49.component.PanelTransparan();
        panelTransparan2 = new pkl49.component.PanelTransparan();
        label14 = new pkl49.component.Label();
        panelTransparan3 = new pkl49.component.PanelTransparan();
        label15 = new pkl49.component.Label();
        label16 = new pkl49.component.Label();
        label17 = new pkl49.component.Label();
        label18 = new pkl49.component.Label();
        panelTransparan4 = new pkl49.component.PanelTransparan();
        label19 = new pkl49.component.Label();
        label20 = new pkl49.component.Label();
        panelTransparan5 = new pkl49.component.PanelTransparan();
        label21 = new pkl49.component.Label();
        panelTransparan6 = new pkl49.component.PanelTransparan();
        label22 = new pkl49.component.Label();
        panelTransparan7 = new pkl49.component.PanelTransparan();
        label23 = new pkl49.component.Label();
        label24 = new pkl49.component.Label();
        panelTransparan8 = new pkl49.component.PanelTransparan();
        label25 = new pkl49.component.Label();
        panelTransparan9 = new pkl49.component.PanelTransparan();
        label27 = new pkl49.component.Label();
        label32 = new pkl49.component.Label();
        panelTransparan10 = new pkl49.component.PanelTransparan();
        label29 = new pkl49.component.Label();
        label30 = new pkl49.component.Label();
        panelTransparan11 = new pkl49.component.PanelTransparan();
        label33 = new pkl49.component.Label();
        panelTransparan12 = new pkl49.component.PanelTransparan();
        label34 = new pkl49.component.Label();
        label31 = new pkl49.component.Label();
        panelTransparan13 = new pkl49.component.PanelTransparan();
        label35 = new pkl49.component.Label();
        label36 = new pkl49.component.Label();
        panelTransparan18 = new pkl49.component.PanelTransparan();
        label37 = new pkl49.component.Label();
        panelTransparan14 = new pkl49.component.PanelTransparan();
        label38 = new pkl49.component.Label();
        label45 = new pkl49.component.Label();
        panelTransparan15 = new pkl49.component.PanelTransparan();
        label41 = new pkl49.component.Label();
        label46 = new pkl49.component.Label();
        panelTransparan16 = new pkl49.component.PanelTransparan();
        label44 = new pkl49.component.Label();
        label48 = new pkl49.component.Label();
        panelTransparan17 = new pkl49.component.PanelTransparan();
        label47 = new pkl49.component.Label();
        label49 = new pkl49.component.Label();
        panelTransparan20 = new pkl49.component.PanelTransparan();
        label53 = new pkl49.component.Label();
        label50 = new pkl49.component.Label();
        panelTransparan21 = new pkl49.component.PanelTransparan();
        label55 = new pkl49.component.Label();
        label54 = new pkl49.component.Label();
        panelTransparan22 = new pkl49.component.PanelTransparan();
        label57 = new pkl49.component.Label();
        label58 = new pkl49.component.Label();
        panelTransparan19 = new pkl49.component.PanelTransparan();
        label39 = new pkl49.component.Label();
        panelTransparan23 = new pkl49.component.PanelTransparan();
        label59 = new pkl49.component.Label();
        label60 = new pkl49.component.Label();
        label52 = new pkl49.component.Label();
        panelTransparan24 = new pkl49.component.PanelTransparan();
        label40 = new pkl49.component.Label();
        label51 = new pkl49.component.Label();
        panelTransparan25 = new pkl49.component.PanelTransparan();
        label42 = new pkl49.component.Label();
        label43 = new pkl49.component.Label();
        panelTransparan26 = new pkl49.component.PanelTransparan();
        label61 = new pkl49.component.Label();
        label62 = new pkl49.component.Label();
        panelTransparan27 = new pkl49.component.PanelTransparan();
        label56 = new pkl49.component.Label();
        panelTransparan28 = new pkl49.component.PanelTransparan();
        label63 = new pkl49.component.Label();
        label64 = new pkl49.component.Label();
        panelTransparan29 = new pkl49.component.PanelTransparan();
        txtB7AK2_1A = new pkl49.component.TextField();
        panelTransparan30 = new pkl49.component.PanelTransparan();
        txtB7AK2_1B = new pkl49.component.TextField();
        panelTransparan31 = new pkl49.component.PanelTransparan();
        txtB7AK2_2 = new pkl49.component.TextField();
        panelTransparan32 = new pkl49.component.PanelTransparan();
        txtB7AK2_3A = new pkl49.component.TextField();
        panelTransparan33 = new pkl49.component.PanelTransparan();
        txtB7AK2_3B = new pkl49.component.TextField();
        panelTransparan34 = new pkl49.component.PanelTransparan();
        txtB7AK2_4 = new pkl49.component.TextField();
        panelTransparan35 = new pkl49.component.PanelTransparan();
        txtB7AK2_5A = new pkl49.component.TextField();
        panelTransparan36 = new pkl49.component.PanelTransparan();
        txtB7AK2_5B = new pkl49.component.TextField();
        panelTransparan37 = new pkl49.component.PanelTransparan();
        txtB7AK2_6 = new pkl49.component.TextField();
        panelTransparan38 = new pkl49.component.PanelTransparan();
        txtB7AK2_7 = new pkl49.component.TextField();
        panelTransparan39 = new pkl49.component.PanelTransparan();
        txtB7AK2_8 = new pkl49.component.TextField();
        panelTransparan40 = new pkl49.component.PanelTransparan();
        txtB7AK2_9 = new pkl49.component.TextField();
        panelTransparan41 = new pkl49.component.PanelTransparan();
        txtB7AK2_10 = new pkl49.component.TextField();
        panelTransparan42 = new pkl49.component.PanelTransparan();
        txtB7AK2_11 = new pkl49.component.TextField();
        panelTransparan43 = new pkl49.component.PanelTransparan();
        txtB7AK2_12A = new pkl49.component.TextField();
        panelTransparan44 = new pkl49.component.PanelTransparan();
        txtB7AK2_12B = new pkl49.component.TextField();
        panelTransparan45 = new pkl49.component.PanelTransparan();
        txtB7AK2_13A = new pkl49.component.TextField();
        panelTransparan46 = new pkl49.component.PanelTransparan();
        txtB7AK2_13B = new pkl49.component.TextField();
        panelTransparan47 = new pkl49.component.PanelTransparan();
        txtB7AK2_13C = new pkl49.component.TextField();
        panelTransparan48 = new pkl49.component.PanelTransparan();
        txtB7AK2_14A = new pkl49.component.TextField();
        panelTransparan49 = new pkl49.component.PanelTransparan();
        txtB7AK2_14B = new pkl49.component.TextField();
        panelTransparan50 = new pkl49.component.PanelTransparan();
        txtB7AK2_15 = new pkl49.component.TextField();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panelTransparan2.setAlpha(70);
        panelTransparan2.setLayout(new java.awt.GridBagLayout());

        label14.setText("VII. PENGELUARAN RUMAH TANGGA"); // NOI18N
        label14.setFont(new java.awt.Font("Tahoma", 1, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        panelTransparan2.add(label14, gridBagConstraints);

        panelTransparan3.setAlpha(70);
        panelTransparan3.setLayout(new java.awt.GridBagLayout());

        label15.setText("VII.A. PENGELUARAN UNTUK MAKANAN SELAMA SEMINGGU TERAKHIR"); // NOI18N
        label15.setFont(new java.awt.Font("Tahoma", 1, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        panelTransparan3.add(label15, gridBagConstraints);

        label16.setFont(new java.awt.Font("Tahoma", 1, 12));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        panelTransparan3.add(label16, gridBagConstraints);

        label17.setText("               [BERASAL DARI PEMBELIAN, PRODUKSI SENDIRI,"); // NOI18N
        label17.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        panelTransparan3.add(label17, gridBagConstraints);

        label18.setText("                                        DAN PEMBERIAN]"); // NOI18N
        label18.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        panelTransparan3.add(label18, gridBagConstraints);

        panelTransparan4.setAlpha(70);
        panelTransparan4.setLayout(new java.awt.GridBagLayout());

        label19.setText("Jumlah"); // NOI18N
        label19.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelTransparan4.add(label19, gridBagConstraints);

        label20.setText("(Rp)"); // NOI18N
        label20.setFont(new java.awt.Font("Tahoma", 1, 11));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        panelTransparan4.add(label20, gridBagConstraints);

        panelTransparan5.setAlpha(50);
        panelTransparan5.setLayout(new java.awt.GridBagLayout());

        label21.setText("(1)"); // NOI18N
        panelTransparan5.add(label21, new java.awt.GridBagConstraints());

        panelTransparan6.setAlpha(50);
        panelTransparan6.setLayout(new java.awt.GridBagLayout());

        label22.setText("(2)"); // NOI18N
        panelTransparan6.add(label22, new java.awt.GridBagConstraints());

        label23.setText("1. Padi-padian"); // NOI18N
        label23.setFont(new java.awt.Font("Tahoma", 1, 11));

        label24.setText("a. Beras"); // NOI18N

        javax.swing.GroupLayout panelTransparan7Layout = new javax.swing.GroupLayout(panelTransparan7);
        panelTransparan7.setLayout(panelTransparan7Layout);
        panelTransparan7Layout.setHorizontalGroup(
            panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(497, Short.MAX_VALUE))
        );
        panelTransparan7Layout.setVerticalGroup(
            panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        label25.setText("b. Lainnya (jagung, terigu, tepung beras,  tepung jagung, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan8Layout = new javax.swing.GroupLayout(panelTransparan8);
        panelTransparan8.setLayout(panelTransparan8Layout);
        panelTransparan8Layout.setHorizontalGroup(
            panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
        panelTransparan8Layout.setVerticalGroup(
            panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label27.setText("2. Umbi-umbian"); // NOI18N
        label27.setFont(new java.awt.Font("Tahoma", 1, 11));

        label32.setText(" (ketela pohon, ketela rambat, kentang, gaplek, talas, sagu, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan9Layout = new javax.swing.GroupLayout(panelTransparan9);
        panelTransparan9.setLayout(panelTransparan9Layout);
        panelTransparan9Layout.setHorizontalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelTransparan9Layout.setVerticalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label29.setText("3. Ikan/udang/cumi/kerang"); // NOI18N
        label29.setFont(new java.awt.Font("Tahoma", 1, 11));

        label30.setText("a. Segar/basah"); // NOI18N

        javax.swing.GroupLayout panelTransparan10Layout = new javax.swing.GroupLayout(panelTransparan10);
        panelTransparan10.setLayout(panelTransparan10Layout);
        panelTransparan10Layout.setHorizontalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTransparan10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(418, Short.MAX_VALUE))
        );
        panelTransparan10Layout.setVerticalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        label33.setText("b. Asin/diawetkan"); // NOI18N

        javax.swing.GroupLayout panelTransparan11Layout = new javax.swing.GroupLayout(panelTransparan11);
        panelTransparan11.setLayout(panelTransparan11Layout);
        panelTransparan11Layout.setHorizontalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        panelTransparan11Layout.setVerticalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label34.setText(" (daging sapi/kerbau/kambing/domba/babi/ayam, jeroan, hati, limpa, abon, dendeng, dll)"); // NOI18N

        label31.setText("4. Daging"); // NOI18N
        label31.setFont(new java.awt.Font("Tahoma", 1, 11));

        javax.swing.GroupLayout panelTransparan12Layout = new javax.swing.GroupLayout(panelTransparan12);
        panelTransparan12.setLayout(panelTransparan12Layout);
        panelTransparan12Layout.setHorizontalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        panelTransparan12Layout.setVerticalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label35.setText("5. Telur dan susu"); // NOI18N
        label35.setFont(new java.awt.Font("Tahoma", 1, 11));

        label36.setText("a. Telur ayam/itik/puyuh"); // NOI18N

        javax.swing.GroupLayout panelTransparan13Layout = new javax.swing.GroupLayout(panelTransparan13);
        panelTransparan13.setLayout(panelTransparan13Layout);
        panelTransparan13Layout.setHorizontalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan13Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        panelTransparan13Layout.setVerticalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label37.setText("b. Susu murni, susu kental, susu bubuk, dll."); // NOI18N

        javax.swing.GroupLayout panelTransparan18Layout = new javax.swing.GroupLayout(panelTransparan18);
        panelTransparan18.setLayout(panelTransparan18Layout);
        panelTransparan18Layout.setHorizontalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan18Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
        );
        panelTransparan18Layout.setVerticalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label38.setText("6. Sayur-sayuran"); // NOI18N
        label38.setFont(new java.awt.Font("Tahoma", 1, 11));

        label45.setText(" (bayam, kangkung, ketimun,wortel, kacang panjang, buncis, bawang, cabe, tomat, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan14Layout = new javax.swing.GroupLayout(panelTransparan14);
        panelTransparan14.setLayout(panelTransparan14Layout);
        panelTransparan14Layout.setHorizontalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelTransparan14Layout.setVerticalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label41.setText("7. Kacang-kacangan "); // NOI18N
        label41.setFont(new java.awt.Font("Tahoma", 1, 11));

        label46.setText("(kacang tanah/hijau/kedele/merah/tunggak/mete, tahu, tempe, tauco,oncom, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan15Layout = new javax.swing.GroupLayout(panelTransparan15);
        panelTransparan15.setLayout(panelTransparan15Layout);
        panelTransparan15Layout.setHorizontalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        panelTransparan15Layout.setVerticalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label44.setText("8. Buah-buahan "); // NOI18N
        label44.setFont(new java.awt.Font("Tahoma", 1, 11));

        label48.setText("(jeruk, mangga, apel, durian,rambutan, salak, duku, nanas, semangka,pisang, pepaya, dll)"); // NOI18N

        javax.swing.GroupLayout panelTransparan16Layout = new javax.swing.GroupLayout(panelTransparan16);
        panelTransparan16.setLayout(panelTransparan16Layout);
        panelTransparan16Layout.setHorizontalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelTransparan16Layout.setVerticalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label47.setText("9. Minyak dan lemak "); // NOI18N
        label47.setFont(new java.awt.Font("Tahoma", 1, 11));

        label49.setText("(minyak kelapa/goreng,kelapa, mentega, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan17Layout = new javax.swing.GroupLayout(panelTransparan17);
        panelTransparan17.setLayout(panelTransparan17Layout);
        panelTransparan17Layout.setHorizontalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        panelTransparan17Layout.setVerticalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label53.setText("10. Bahan minuman"); // NOI18N
        label53.setFont(new java.awt.Font("Tahoma", 1, 11));

        label50.setText(" (gula pasir, gula merah, teh,kopi, coklat, sirup, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan20Layout = new javax.swing.GroupLayout(panelTransparan20);
        panelTransparan20.setLayout(panelTransparan20Layout);
        panelTransparan20Layout.setHorizontalGroup(
            panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        panelTransparan20Layout.setVerticalGroup(
            panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label53, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label55.setText("11. Bumbu-bumbuan"); // NOI18N
        label55.setFont(new java.awt.Font("Tahoma", 1, 11));

        label54.setText(" (garam, kemiri, ketumbar,merica, terasi, kecap, vetsin, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan21Layout = new javax.swing.GroupLayout(panelTransparan21);
        panelTransparan21.setLayout(panelTransparan21Layout);
        panelTransparan21Layout.setHorizontalGroup(
            panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        panelTransparan21Layout.setVerticalGroup(
            panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label55, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label57.setText("12. Konsumsi Lainnya"); // NOI18N
        label57.setFont(new java.awt.Font("Tahoma", 1, 11));

        label58.setText("a. Mie instant, mie basah, bihun, makaroni/ mie kering."); // NOI18N

        javax.swing.GroupLayout panelTransparan22Layout = new javax.swing.GroupLayout(panelTransparan22);
        panelTransparan22.setLayout(panelTransparan22Layout);
        panelTransparan22Layout.setHorizontalGroup(
            panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan22Layout.createSequentialGroup()
                .addGroup(panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan22Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan22Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        panelTransparan22Layout.setVerticalGroup(
            panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label57, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label58, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label39.setText("b. Lainnya (kerupuk, emping, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan19Layout = new javax.swing.GroupLayout(panelTransparan19);
        panelTransparan19.setLayout(panelTransparan19Layout);
        panelTransparan19Layout.setHorizontalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan19Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        panelTransparan19Layout.setVerticalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label59.setText("13. Makanan dan minuman jadi"); // NOI18N
        label59.setFont(new java.awt.Font("Tahoma", 1, 11));

        label60.setText("a. Makanan jadi "); // NOI18N

        label52.setText("(roti, biskuit, kue basah, bubur, bakso, gado-gado, nasi rames, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan23Layout = new javax.swing.GroupLayout(panelTransparan23);
        panelTransparan23.setLayout(panelTransparan23Layout);
        panelTransparan23Layout.setHorizontalGroup(
            panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan23Layout.createSequentialGroup()
                .addGroup(panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan23Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        panelTransparan23Layout.setVerticalGroup(
            panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label59, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label60, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label52, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label40.setText("b. Minuman non alkohol "); // NOI18N

        label51.setText("(soft drink, es sirop, limun, air mineral, dll.)"); // NOI18N

        javax.swing.GroupLayout panelTransparan24Layout = new javax.swing.GroupLayout(panelTransparan24);
        panelTransparan24.setLayout(panelTransparan24Layout);
        panelTransparan24Layout.setHorizontalGroup(
            panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan24Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        panelTransparan24Layout.setVerticalGroup(
            panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan24Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label51, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label42.setText("c. Minuman mengandung alkohol"); // NOI18N

        label43.setText(" (bir, anggur, dan minuman keras lainnya)"); // NOI18N

        javax.swing.GroupLayout panelTransparan25Layout = new javax.swing.GroupLayout(panelTransparan25);
        panelTransparan25.setLayout(panelTransparan25Layout);
        panelTransparan25Layout.setHorizontalGroup(
            panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan25Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(196, Short.MAX_VALUE))
        );
        panelTransparan25Layout.setVerticalGroup(
            panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label61.setText("14. Tembakau dan sirih"); // NOI18N
        label61.setFont(new java.awt.Font("Tahoma", 1, 11));

        label62.setText("a. Rokok (rokok kretek, rokok putih, cerutu)"); // NOI18N

        javax.swing.GroupLayout panelTransparan26Layout = new javax.swing.GroupLayout(panelTransparan26);
        panelTransparan26.setLayout(panelTransparan26Layout);
        panelTransparan26Layout.setHorizontalGroup(
            panelTransparan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan26Layout.createSequentialGroup()
                .addGroup(panelTransparan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan26Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan26Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(348, Short.MAX_VALUE))
        );
        panelTransparan26Layout.setVerticalGroup(
            panelTransparan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label61, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label62, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label56.setText("b. Lainnya (sirih, pinang, tembakau, dan lainnya)"); // NOI18N

        javax.swing.GroupLayout panelTransparan27Layout = new javax.swing.GroupLayout(panelTransparan27);
        panelTransparan27.setLayout(panelTransparan27Layout);
        panelTransparan27Layout.setHorizontalGroup(
            panelTransparan27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan27Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        panelTransparan27Layout.setVerticalGroup(
            panelTransparan27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan27Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label56, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label63.setText("15. Jumlah makanan"); // NOI18N
        label63.setFont(new java.awt.Font("Tahoma", 1, 11));

        label64.setText("(Rincaian 1 s.d. 14)"); // NOI18N

        javax.swing.GroupLayout panelTransparan28Layout = new javax.swing.GroupLayout(panelTransparan28);
        panelTransparan28.setLayout(panelTransparan28Layout);
        panelTransparan28Layout.setHorizontalGroup(
            panelTransparan28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan28Layout.createSequentialGroup()
                .addGroup(panelTransparan28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelTransparan28Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelTransparan28Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(label64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        panelTransparan28Layout.setVerticalGroup(
            panelTransparan28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label63, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtB7AK2_1A.setColumns(10);
        txtB7AK2_1A.setCharType(1);
        txtB7AK2_1A.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_1A.setLength(10);
        txtB7AK2_1A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_1A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan29.add(txtB7AK2_1A);

        txtB7AK2_1B.setColumns(10);
        txtB7AK2_1B.setCharType(1);
        txtB7AK2_1B.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_1B.setLength(10);
        txtB7AK2_1B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_1B.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan30.add(txtB7AK2_1B);

        txtB7AK2_2.setColumns(10);
        txtB7AK2_2.setCharType(1);
        txtB7AK2_2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_2.setLength(10);
        txtB7AK2_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan31.add(txtB7AK2_2);

        txtB7AK2_3A.setColumns(10);
        txtB7AK2_3A.setCharType(1);
        txtB7AK2_3A.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_3A.setLength(10);
        txtB7AK2_3A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_3A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan32.add(txtB7AK2_3A);

        txtB7AK2_3B.setColumns(10);
        txtB7AK2_3B.setCharType(1);
        txtB7AK2_3B.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_3B.setLength(10);
        txtB7AK2_3B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_3B.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan33.add(txtB7AK2_3B);

        txtB7AK2_4.setColumns(10);
        txtB7AK2_4.setCharType(1);
        txtB7AK2_4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_4.setLength(10);
        txtB7AK2_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan34.add(txtB7AK2_4);

        txtB7AK2_5A.setColumns(10);
        txtB7AK2_5A.setCharType(1);
        txtB7AK2_5A.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_5A.setLength(10);
        txtB7AK2_5A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_5A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan35.add(txtB7AK2_5A);

        txtB7AK2_5B.setColumns(10);
        txtB7AK2_5B.setCharType(1);
        txtB7AK2_5B.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_5B.setLength(10);
        txtB7AK2_5B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_5B.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan36.add(txtB7AK2_5B);

        txtB7AK2_6.setColumns(10);
        txtB7AK2_6.setCharType(1);
        txtB7AK2_6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_6.setLength(10);
        txtB7AK2_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan37.add(txtB7AK2_6);

        txtB7AK2_7.setColumns(10);
        txtB7AK2_7.setCharType(1);
        txtB7AK2_7.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_7.setLength(10);
        txtB7AK2_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan38.add(txtB7AK2_7);

        txtB7AK2_8.setColumns(10);
        txtB7AK2_8.setCharType(1);
        txtB7AK2_8.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_8.setLength(10);
        txtB7AK2_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_8.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan39.add(txtB7AK2_8);

        txtB7AK2_9.setColumns(10);
        txtB7AK2_9.setCharType(1);
        txtB7AK2_9.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_9.setLength(10);
        txtB7AK2_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_9.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan40.add(txtB7AK2_9);

        txtB7AK2_10.setColumns(10);
        txtB7AK2_10.setCharType(1);
        txtB7AK2_10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_10.setLength(10);
        txtB7AK2_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan41.add(txtB7AK2_10);

        txtB7AK2_11.setColumns(10);
        txtB7AK2_11.setCharType(1);
        txtB7AK2_11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_11.setLength(10);
        txtB7AK2_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_11.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan42.add(txtB7AK2_11);

        txtB7AK2_12A.setColumns(10);
        txtB7AK2_12A.setCharType(1);
        txtB7AK2_12A.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_12A.setLength(10);
        txtB7AK2_12A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_12A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan43.add(txtB7AK2_12A);

        txtB7AK2_12B.setColumns(10);
        txtB7AK2_12B.setCharType(1);
        txtB7AK2_12B.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_12B.setLength(10);
        txtB7AK2_12B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_12B.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan44.add(txtB7AK2_12B);

        txtB7AK2_13A.setColumns(10);
        txtB7AK2_13A.setCharType(1);
        txtB7AK2_13A.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_13A.setLength(10);
        txtB7AK2_13A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_13A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan45.add(txtB7AK2_13A);

        txtB7AK2_13B.setColumns(10);
        txtB7AK2_13B.setCharType(1);
        txtB7AK2_13B.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_13B.setLength(10);
        txtB7AK2_13B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_13B.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan46.add(txtB7AK2_13B);

        txtB7AK2_13C.setColumns(10);
        txtB7AK2_13C.setCharType(1);
        txtB7AK2_13C.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_13C.setLength(10);
        txtB7AK2_13C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_13C.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan47.add(txtB7AK2_13C);

        txtB7AK2_14A.setColumns(10);
        txtB7AK2_14A.setCharType(1);
        txtB7AK2_14A.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_14A.setLength(10);
        txtB7AK2_14A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_14A.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan48.add(txtB7AK2_14A);

        txtB7AK2_14B.setColumns(10);
        txtB7AK2_14B.setCharType(1);
        txtB7AK2_14B.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_14B.setLength(10);
        txtB7AK2_14B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_14B.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan49.add(txtB7AK2_14B);

        txtB7AK2_15.setColumns(10);
        txtB7AK2_15.setCharType(1);
        txtB7AK2_15.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));
        txtB7AK2_15.setLength(10);
        txtB7AK2_15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAction(evt);
            }
        });
        txtB7AK2_15.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTxt(evt);
            }
        });
        panelTransparan50.add(txtB7AK2_15);

        javax.swing.GroupLayout panelTransparan1Layout = new javax.swing.GroupLayout(panelTransparan1);
        panelTransparan1.setLayout(panelTransparan1Layout);
        panelTransparan1Layout.setHorizontalGroup(
            panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
            .addGroup(panelTransparan1Layout.createSequentialGroup()
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTransparan27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(panelTransparan3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                    .addComponent(panelTransparan9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan4, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan30, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan34, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan36, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan38, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan40, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan42, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan43, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan46, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan47, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan48, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan49, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(panelTransparan50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)))
        );
        panelTransparan1Layout.setVerticalGroup(
            panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan1Layout.createSequentialGroup()
                .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan4, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan29, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan30, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan31, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan32, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan33, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan34, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan35, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan36, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan37, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan38, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan39, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan40, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan41, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan42, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan43, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan44, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan45, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan46, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan47, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan48, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan49, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(panelTransparan27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan50, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(panelTransparan28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelScrollLayout = new javax.swing.GroupLayout(panelScroll);
        panelScroll.setLayout(panelScrollLayout);
        panelScrollLayout.setHorizontalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelScrollLayout.setVerticalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        scroolPane1.setViewportView(panelScroll);

        add(scroolPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void focusTxt(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusTxt
        panelScroll.scrollRectToVisible(evt.getComponent().getParent().getBounds(null));
    }//GEN-LAST:event_focusTxt

    private void txtAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAction
        
    }//GEN-LAST:event_txtAction


    public List<TextField> getListBlok7A(){
        return  listBlok7A;
    }

    public void setListText(){
        
        listBlok7A=new ArrayList<TextField>();
        listBlok7A.add(txtB7AK2_1A);//0
        listBlok7A.add(txtB7AK2_1B);
        listBlok7A.add(txtB7AK2_2);
        listBlok7A.add(txtB7AK2_3A);
        listBlok7A.add(txtB7AK2_3B);
        listBlok7A.add(txtB7AK2_4);//5
        listBlok7A.add(txtB7AK2_5A);
        listBlok7A.add(txtB7AK2_5B);
        listBlok7A.add(txtB7AK2_6);
        listBlok7A.add(txtB7AK2_7);
        listBlok7A.add(txtB7AK2_8);//10
        listBlok7A.add(txtB7AK2_9);
        listBlok7A.add(txtB7AK2_10);
        listBlok7A.add(txtB7AK2_11);
        listBlok7A.add(txtB7AK2_12A);
        listBlok7A.add(txtB7AK2_12B);//15
        listBlok7A.add(txtB7AK2_13A);
        listBlok7A.add(txtB7AK2_13B);
        listBlok7A.add(txtB7AK2_13C);
        listBlok7A.add(txtB7AK2_14A);
        listBlok7A.add(txtB7AK2_14B);//20
        listBlok7A.add(txtB7AK2_15);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.Label label14;
    private pkl49.component.Label label15;
    private pkl49.component.Label label16;
    private pkl49.component.Label label17;
    private pkl49.component.Label label18;
    private pkl49.component.Label label19;
    private pkl49.component.Label label20;
    private pkl49.component.Label label21;
    private pkl49.component.Label label22;
    private pkl49.component.Label label23;
    private pkl49.component.Label label24;
    private pkl49.component.Label label25;
    private pkl49.component.Label label27;
    private pkl49.component.Label label29;
    private pkl49.component.Label label30;
    private pkl49.component.Label label31;
    private pkl49.component.Label label32;
    private pkl49.component.Label label33;
    private pkl49.component.Label label34;
    private pkl49.component.Label label35;
    private pkl49.component.Label label36;
    private pkl49.component.Label label37;
    private pkl49.component.Label label38;
    private pkl49.component.Label label39;
    private pkl49.component.Label label40;
    private pkl49.component.Label label41;
    private pkl49.component.Label label42;
    private pkl49.component.Label label43;
    private pkl49.component.Label label44;
    private pkl49.component.Label label45;
    private pkl49.component.Label label46;
    private pkl49.component.Label label47;
    private pkl49.component.Label label48;
    private pkl49.component.Label label49;
    private pkl49.component.Label label50;
    private pkl49.component.Label label51;
    private pkl49.component.Label label52;
    private pkl49.component.Label label53;
    private pkl49.component.Label label54;
    private pkl49.component.Label label55;
    private pkl49.component.Label label56;
    private pkl49.component.Label label57;
    private pkl49.component.Label label58;
    private pkl49.component.Label label59;
    private pkl49.component.Label label60;
    private pkl49.component.Label label61;
    private pkl49.component.Label label62;
    private pkl49.component.Label label63;
    private pkl49.component.Label label64;
    private pkl49.component.PanelTransparan panelScroll;
    private pkl49.component.PanelTransparan panelTransparan1;
    private pkl49.component.PanelTransparan panelTransparan10;
    private pkl49.component.PanelTransparan panelTransparan11;
    private pkl49.component.PanelTransparan panelTransparan12;
    private pkl49.component.PanelTransparan panelTransparan13;
    private pkl49.component.PanelTransparan panelTransparan14;
    private pkl49.component.PanelTransparan panelTransparan15;
    private pkl49.component.PanelTransparan panelTransparan16;
    private pkl49.component.PanelTransparan panelTransparan17;
    private pkl49.component.PanelTransparan panelTransparan18;
    private pkl49.component.PanelTransparan panelTransparan19;
    private pkl49.component.PanelTransparan panelTransparan2;
    private pkl49.component.PanelTransparan panelTransparan20;
    private pkl49.component.PanelTransparan panelTransparan21;
    private pkl49.component.PanelTransparan panelTransparan22;
    private pkl49.component.PanelTransparan panelTransparan23;
    private pkl49.component.PanelTransparan panelTransparan24;
    private pkl49.component.PanelTransparan panelTransparan25;
    private pkl49.component.PanelTransparan panelTransparan26;
    private pkl49.component.PanelTransparan panelTransparan27;
    private pkl49.component.PanelTransparan panelTransparan28;
    private pkl49.component.PanelTransparan panelTransparan29;
    private pkl49.component.PanelTransparan panelTransparan3;
    private pkl49.component.PanelTransparan panelTransparan30;
    private pkl49.component.PanelTransparan panelTransparan31;
    private pkl49.component.PanelTransparan panelTransparan32;
    private pkl49.component.PanelTransparan panelTransparan33;
    private pkl49.component.PanelTransparan panelTransparan34;
    private pkl49.component.PanelTransparan panelTransparan35;
    private pkl49.component.PanelTransparan panelTransparan36;
    private pkl49.component.PanelTransparan panelTransparan37;
    private pkl49.component.PanelTransparan panelTransparan38;
    private pkl49.component.PanelTransparan panelTransparan39;
    private pkl49.component.PanelTransparan panelTransparan4;
    private pkl49.component.PanelTransparan panelTransparan40;
    private pkl49.component.PanelTransparan panelTransparan41;
    private pkl49.component.PanelTransparan panelTransparan42;
    private pkl49.component.PanelTransparan panelTransparan43;
    private pkl49.component.PanelTransparan panelTransparan44;
    private pkl49.component.PanelTransparan panelTransparan45;
    private pkl49.component.PanelTransparan panelTransparan46;
    private pkl49.component.PanelTransparan panelTransparan47;
    private pkl49.component.PanelTransparan panelTransparan48;
    private pkl49.component.PanelTransparan panelTransparan49;
    private pkl49.component.PanelTransparan panelTransparan5;
    private pkl49.component.PanelTransparan panelTransparan50;
    private pkl49.component.PanelTransparan panelTransparan6;
    private pkl49.component.PanelTransparan panelTransparan7;
    private pkl49.component.PanelTransparan panelTransparan8;
    private pkl49.component.PanelTransparan panelTransparan9;
    private pkl49.component.ScroolPane scroolPane1;
    private pkl49.component.TextField txtB7AK2_10;
    private pkl49.component.TextField txtB7AK2_11;
    private pkl49.component.TextField txtB7AK2_12A;
    private pkl49.component.TextField txtB7AK2_12B;
    private pkl49.component.TextField txtB7AK2_13A;
    private pkl49.component.TextField txtB7AK2_13B;
    private pkl49.component.TextField txtB7AK2_13C;
    private pkl49.component.TextField txtB7AK2_14A;
    private pkl49.component.TextField txtB7AK2_14B;
    private pkl49.component.TextField txtB7AK2_15;
    private pkl49.component.TextField txtB7AK2_1A;
    private pkl49.component.TextField txtB7AK2_1B;
    private pkl49.component.TextField txtB7AK2_2;
    private pkl49.component.TextField txtB7AK2_3A;
    private pkl49.component.TextField txtB7AK2_3B;
    private pkl49.component.TextField txtB7AK2_4;
    private pkl49.component.TextField txtB7AK2_5A;
    private pkl49.component.TextField txtB7AK2_5B;
    private pkl49.component.TextField txtB7AK2_6;
    private pkl49.component.TextField txtB7AK2_7;
    private pkl49.component.TextField txtB7AK2_8;
    private pkl49.component.TextField txtB7AK2_9;
    // End of variables declaration//GEN-END:variables

}
