/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hlm.java
 *
 * Created on Jan 15, 2010, 9:35:13 AM
 */

package pkl49.view;

import java.awt.event.FocusEvent;
import java.util.ArrayList;
import java.util.List;
import pkl49.component.Label;
import pkl49.component.TextField;

/**
 *
 * @author Junedi Walfy
 */
public class Halaman1 extends javax.swing.JPanel {
    private List<TextField> listHalaman1;
    /** Creates new form Hlm */
    public Halaman1() {
        initComponents();
        addList();
        //Validasi val=new Validasi(listHalaman1, "Hal1",);
        addScroll();
        for(int i=0;i<listHalaman1.size();i++){
            listHalaman1.get(i).setFocusTraversalKeysEnabled(false);
        }
    }

    public Label getLabelDesa() {
        return labelDesa;
    }

    public Label getLabelKab() {
        return labelKab;
    }

    public Label getLabelKec() {
        return labelKec;
    }




    public void addScroll(){
        for(int i=0;i<listHalaman1.size();i++){
            listHalaman1.get(i).addFocusListener(new java.awt.event.FocusAdapter() {
                @Override
                public void focusGained(java.awt.event.FocusEvent evt) {
                    focusTxt(evt);
                }

                private void focusTxt(FocusEvent evt) {
                    panelTabel.scrollRectToVisible(evt.getComponent().getParent().getParent().getBounds(null));
                }
            });
        }
    }
    public void addList(){
        listHalaman1=new ArrayList<TextField>();
        listHalaman1.add(txtB1R1);//0
        listHalaman1.add(txtB1R2);
        listHalaman1.add(txtB1R3);
        listHalaman1.add(txtB1R4);
        listHalaman1.add(txtB1R5);
        listHalaman1.add(txtB1R6);
        listHalaman1.add(txtB1R7);
        listHalaman1.add(txtB1R8);
        listHalaman1.add(txtB1R9);//8
        listHalaman1.add(txtB2R1);
        listHalaman1.add(txtB2R2);
        listHalaman1.add(txtB2R3);
        listHalaman1.add(txtB2R4);
        listHalaman1.add(txtB2R5);
        listHalaman1.add(txtB2R6);
        listHalaman1.add(txtB3R1);
        listHalaman1.add(txtB3R2);
        listHalaman1.add(txtB3R3);
        listHalaman1.add(txtB3R5);
        listHalaman1.add(txtB3R6);
        listHalaman1.add(txtB3R7);

    }

    public List<TextField> getListHalaman1() {
        return listHalaman1;
    }

    public TextField getTxtB3R7() {
        return txtB3R7;
    }


    public TextField getTxtB2R1() {
        return txtB2R1;
    }

    public TextField getTxtB1R1() {
        return txtB1R1;
    }

    public TextField getTxtB1R2() {
        return txtB1R2;
    }

    public TextField getTxtB1R3() {
        return txtB1R3;
    }

    public TextField getTxtB1R4() {
        return txtB1R4;
    }

    public TextField getTxtB1R5() {
        return txtB1R5;
    }

    public TextField getTxtB1R6() {
        return txtB1R6;
    }

    public TextField getTxtB1R7() {
        return txtB1R7;
    }

    public TextField getTxtB1R8() {
        return txtB1R8;
    }

    public TextField getTxtB1R9() {
        return txtB1R9;
    }

    public TextField getTxtB2R2() {
        return txtB2R2;
    }

    public TextField getTxtB2R3() {
        return txtB2R3;
    }

    public TextField getTxtB2R4() {
        return txtB2R4;
    }

    public TextField getTxtB2R5() {
        return txtB2R5;
    }

    public TextField getTxtB2R6() {
        return txtB2R6;
    }

    public TextField getTxtB3R1() {
        return txtB3R5;
    }

    public TextField getTxtB3R2() {
        return txtB3R2;
    }

    public TextField getTxtB3R3() {
        return txtB3R7;
    }

    public TextField getTxtB3R4() {
        return txtB3R1;
    }

    public TextField getTxtB3R5() {
        return txtB3R6;
    }

    public TextField getTxtB3R6() {
        return txtB3R3;
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroolPane1 = new pkl49.component.ScroolPane();
        panelScroll = new pkl49.component.PanelTransparan();
        panelTabel = new pkl49.component.PanelTransparan();
        panelTransparan1 = new pkl49.component.PanelTransparan();
        panelTransparan2 = new pkl49.component.PanelTransparan();
        label1 = new pkl49.component.Label();
        panelTransparan4 = new pkl49.component.PanelTransparan();
        label9 = new pkl49.component.Label();
        txtB1R8 = new pkl49.component.TextField();
        panelTransparan5 = new pkl49.component.PanelTransparan();
        label10 = new pkl49.component.Label();
        txtB1R9 = new pkl49.component.TextField();
        panelTransparan24 = new pkl49.component.PanelTransparan();
        label31 = new pkl49.component.Label();
        txtB1R2 = new pkl49.component.TextField();
        panelTransparan25 = new pkl49.component.PanelTransparan();
        label32 = new pkl49.component.Label();
        labelKec = new pkl49.component.Label();
        txtB1R3 = new pkl49.component.TextField();
        panelTransparan26 = new pkl49.component.PanelTransparan();
        label33 = new pkl49.component.Label();
        txtB1R4 = new pkl49.component.TextField();
        labelDesa = new pkl49.component.Label();
        panelTransparan27 = new pkl49.component.PanelTransparan();
        label34 = new pkl49.component.Label();
        txtB1R5 = new pkl49.component.TextField();
        panelTransparan28 = new pkl49.component.PanelTransparan();
        label35 = new pkl49.component.Label();
        txtB1R6 = new pkl49.component.TextField();
        panelTransparan29 = new pkl49.component.PanelTransparan();
        label36 = new pkl49.component.Label();
        txtB1R7 = new pkl49.component.TextField();
        panelTransparan30 = new pkl49.component.PanelTransparan();
        label37 = new pkl49.component.Label();
        txtB1R1 = new pkl49.component.TextField();
        labelKab = new pkl49.component.Label();
        panelTransparan6 = new pkl49.component.PanelTransparan();
        panelTransparan7 = new pkl49.component.PanelTransparan();
        labelWaktu1 = new pkl49.component.LabelWaktu();
        panelTransparan8 = new pkl49.component.PanelTransparan();
        label11 = new pkl49.component.Label();
        txtB2R1 = new pkl49.component.TextField();
        panelTransparan9 = new pkl49.component.PanelTransparan();
        label12 = new pkl49.component.Label();
        txtB2R2 = new pkl49.component.TextField();
        panelTransparan10 = new pkl49.component.PanelTransparan();
        label13 = new pkl49.component.Label();
        txtB2R3 = new pkl49.component.TextField();
        panelTransparan13 = new pkl49.component.PanelTransparan();
        label25 = new pkl49.component.Label();
        txtB2R4 = new pkl49.component.TextField();
        panelTransparan14 = new pkl49.component.PanelTransparan();
        label26 = new pkl49.component.Label();
        txtB2R5 = new pkl49.component.TextField();
        panelTransparan21 = new pkl49.component.PanelTransparan();
        label27 = new pkl49.component.Label();
        txtB2R6 = new pkl49.component.TextField();
        panelTransparan11 = new pkl49.component.PanelTransparan();
        panelTransparan12 = new pkl49.component.PanelTransparan();
        label14 = new pkl49.component.Label();
        p1 = new pkl49.component.PanelTransparan();
        label15 = new pkl49.component.Label();
        p2 = new pkl49.component.PanelTransparan();
        label16 = new pkl49.component.Label();
        panelTransparan15 = new pkl49.component.PanelTransparan();
        label17 = new pkl49.component.Label();
        txtB3R1 = new pkl49.component.TextField();
        panelTransparan16 = new pkl49.component.PanelTransparan();
        label18 = new pkl49.component.Label();
        txtB3R2 = new pkl49.component.TextField();
        panelTransparan17 = new pkl49.component.PanelTransparan();
        label19 = new pkl49.component.Label();
        txtB3R3 = new pkl49.component.TextField();
        panelTransparan22 = new pkl49.component.PanelTransparan();
        label20 = new pkl49.component.Label();
        panelTransparan18 = new pkl49.component.PanelTransparan();
        label21 = new pkl49.component.Label();
        txtB3R5 = new pkl49.component.TextField();
        panelTransparan19 = new pkl49.component.PanelTransparan();
        label22 = new pkl49.component.Label();
        txtB3R6 = new pkl49.component.TextField();
        panelTransparan20 = new pkl49.component.PanelTransparan();
        label23 = new pkl49.component.Label();
        txtB3R7 = new pkl49.component.TextField();
        panelTransparan23 = new pkl49.component.PanelTransparan();
        label24 = new pkl49.component.Label();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panelTabel.setBorder(null);

        panelTransparan2.setAlpha(70);

        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("I. PENGENALAN TEMPAT"); // NOI18N
        label1.setFont(new java.awt.Font("Tahoma", 1, 12));

        javax.swing.GroupLayout panelTransparan2Layout = new javax.swing.GroupLayout(panelTransparan2);
        panelTransparan2.setLayout(panelTransparan2Layout);
        panelTransparan2Layout.setHorizontalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTransparan2Layout.setVerticalGroup(
            panelTransparan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label9.setBackground(new java.awt.Color(255, 51, 102));
        label9.setText("8. Nama Kepala Rumah Tangga"); // NOI18N

        txtB1R8.setCharType(2);
        txtB1R8.setLength(35);

        javax.swing.GroupLayout panelTransparan4Layout = new javax.swing.GroupLayout(panelTransparan4);
        panelTransparan4.setLayout(panelTransparan4Layout);
        panelTransparan4Layout.setHorizontalGroup(
            panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtB1R8, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTransparan4Layout.setVerticalGroup(
            panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label10.setText("9. Alamat"); // NOI18N

        txtB1R9.setCharType(1);
        txtB1R9.setLength(60);

        javax.swing.GroupLayout panelTransparan5Layout = new javax.swing.GroupLayout(panelTransparan5);
        panelTransparan5.setLayout(panelTransparan5Layout);
        panelTransparan5Layout.setHorizontalGroup(
            panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtB1R9, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTransparan5Layout.setVerticalGroup(
            panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label31.setText("2. Klasifikasi Strata"); // NOI18N

        txtB1R2.setMaxDigit('3');
        txtB1R2.setMinDigit('1');

        javax.swing.GroupLayout panelTransparan24Layout = new javax.swing.GroupLayout(panelTransparan24);
        panelTransparan24.setLayout(panelTransparan24Layout);
        panelTransparan24Layout.setHorizontalGroup(
            panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                .addComponent(txtB1R2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan24Layout.setVerticalGroup(
            panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan24Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label32.setText("3. Kecamatan"); // NOI18N

        labelKec.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKec.setText(" "); // NOI18N
        labelKec.setFont(new java.awt.Font("Tahoma", 1, 11));

        txtB1R3.setColumns(3);
        txtB1R3.setLength(3);

        javax.swing.GroupLayout panelTransparan25Layout = new javax.swing.GroupLayout(panelTransparan25);
        panelTransparan25.setLayout(panelTransparan25Layout);
        panelTransparan25Layout.setHorizontalGroup(
            panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan25Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(labelKec, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtB1R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan25Layout.setVerticalGroup(
            panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan25Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label33.setText("4. Desa/Kelurahan"); // NOI18N

        txtB1R4.setLength(3);

        labelDesa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDesa.setText(" "); // NOI18N
        labelDesa.setFont(new java.awt.Font("Tahoma", 1, 11));

        javax.swing.GroupLayout panelTransparan26Layout = new javax.swing.GroupLayout(panelTransparan26);
        panelTransparan26.setLayout(panelTransparan26Layout);
        panelTransparan26Layout.setHorizontalGroup(
            panelTransparan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan26Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(labelDesa, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtB1R4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan26Layout.setVerticalGroup(
            panelTransparan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan26Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label34.setText("5. Nomor Blok Sensus"); // NOI18N

        txtB1R5.setCharType(1);
        txtB1R5.setLength(4);

        javax.swing.GroupLayout panelTransparan27Layout = new javax.swing.GroupLayout(panelTransparan27);
        panelTransparan27.setLayout(panelTransparan27Layout);
        panelTransparan27Layout.setHorizontalGroup(
            panelTransparan27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan27Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                .addComponent(txtB1R5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan27Layout.setVerticalGroup(
            panelTransparan27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label35.setText("6. Nomor Urut Rumah Tangga"); // NOI18N

        txtB1R6.setLength(3);
        txtB1R6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtB1R6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTransparan28Layout = new javax.swing.GroupLayout(panelTransparan28);
        panelTransparan28.setLayout(panelTransparan28Layout);
        panelTransparan28Layout.setHorizontalGroup(
            panelTransparan28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 492, Short.MAX_VALUE)
                .addComponent(txtB1R6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan28Layout.setVerticalGroup(
            panelTransparan28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan28Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label36.setText("7. Nomor Urut Rumah Tangga Sampel "); // NOI18N

        txtB1R7.setLength(2);

        javax.swing.GroupLayout panelTransparan29Layout = new javax.swing.GroupLayout(panelTransparan29);
        panelTransparan29.setLayout(panelTransparan29Layout);
        panelTransparan29Layout.setHorizontalGroup(
            panelTransparan29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addComponent(txtB1R7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan29Layout.setVerticalGroup(
            panelTransparan29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan29Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label37.setText("1. Kabupaten/ Kota"); // NOI18N

        txtB1R1.setLength(2);

        labelKab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelKab.setText(" "); // NOI18N
        labelKab.setFont(new java.awt.Font("Tahoma", 1, 11));

        javax.swing.GroupLayout panelTransparan30Layout = new javax.swing.GroupLayout(panelTransparan30);
        panelTransparan30.setLayout(panelTransparan30Layout);
        panelTransparan30Layout.setHorizontalGroup(
            panelTransparan30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan30Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(labelKab, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtB1R1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan30Layout.setVerticalGroup(
            panelTransparan30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTransparan1Layout = new javax.swing.GroupLayout(panelTransparan1);
        panelTransparan1.setLayout(panelTransparan1Layout);
        panelTransparan1Layout.setHorizontalGroup(
            panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTransparan1Layout.setVerticalGroup(
            panelTransparan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan1Layout.createSequentialGroup()
                .addComponent(panelTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(panelTransparan5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelTransparan7.setAlpha(70);

        labelWaktu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWaktu1.setText("II. RINGKASAN BLOK IV"); // NOI18N
        labelWaktu1.setFont(new java.awt.Font("Tahoma", 1, 12));

        javax.swing.GroupLayout panelTransparan7Layout = new javax.swing.GroupLayout(panelTransparan7);
        panelTransparan7.setLayout(panelTransparan7Layout);
        panelTransparan7Layout.setHorizontalGroup(
            panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWaktu1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTransparan7Layout.setVerticalGroup(
            panelTransparan7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelWaktu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        label11.setText("1. Banyaknya Anggota Rumah Tangga :"); // NOI18N

        txtB2R1.setLength(2);

        javax.swing.GroupLayout panelTransparan8Layout = new javax.swing.GroupLayout(panelTransparan8);
        panelTransparan8.setLayout(panelTransparan8Layout);
        panelTransparan8Layout.setHorizontalGroup(
            panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addComponent(txtB2R1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan8Layout.setVerticalGroup(
            panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB2R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        label12.setText("2. Banyaknya Anggota Rumah Tangga yang berumur <1 tahun  :"); // NOI18N

        txtB2R2.setLength(2);

        javax.swing.GroupLayout panelTransparan9Layout = new javax.swing.GroupLayout(panelTransparan9);
        panelTransparan9.setLayout(panelTransparan9Layout);
        panelTransparan9Layout.setHorizontalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 334, Short.MAX_VALUE)
                .addComponent(txtB2R2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan9Layout.setVerticalGroup(
            panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB2R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label13.setText("3. Banyaknya Anggota Rumah Tangga yang berumur 1-4  tahun  :"); // NOI18N

        txtB2R3.setLength(2);

        javax.swing.GroupLayout panelTransparan10Layout = new javax.swing.GroupLayout(panelTransparan10);
        panelTransparan10.setLayout(panelTransparan10Layout);
        panelTransparan10Layout.setHorizontalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(txtB2R3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan10Layout.setVerticalGroup(
            panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB2R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        label25.setText("4. Banyaknya Anggota Rumah Tangga yang berumur 5 - 14 tahun :"); // NOI18N

        txtB2R4.setLength(2);

        javax.swing.GroupLayout panelTransparan13Layout = new javax.swing.GroupLayout(panelTransparan13);
        panelTransparan13.setLayout(panelTransparan13Layout);
        panelTransparan13Layout.setHorizontalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 322, Short.MAX_VALUE)
                .addComponent(txtB2R4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan13Layout.setVerticalGroup(
            panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB2R4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label26.setText("5. Banyaknya Anggota Rumah Tangga yang berumur 15-64  tahun  :"); // NOI18N

        txtB2R5.setLength(2);

        javax.swing.GroupLayout panelTransparan14Layout = new javax.swing.GroupLayout(panelTransparan14);
        panelTransparan14.setLayout(panelTransparan14Layout);
        panelTransparan14Layout.setHorizontalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 315, Short.MAX_VALUE)
                .addComponent(txtB2R5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan14Layout.setVerticalGroup(
            panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB2R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label27.setText("6. Banyaknya Anggota Rumah Tangga yang berumur 65+  tahun  :"); // NOI18N

        txtB2R6.setLength(2);

        javax.swing.GroupLayout panelTransparan21Layout = new javax.swing.GroupLayout(panelTransparan21);
        panelTransparan21.setLayout(panelTransparan21Layout);
        panelTransparan21Layout.setHorizontalGroup(
            panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                .addComponent(txtB2R6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan21Layout.setVerticalGroup(
            panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB2R6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelTransparan6Layout = new javax.swing.GroupLayout(panelTransparan6);
        panelTransparan6.setLayout(panelTransparan6Layout);
        panelTransparan6Layout.setHorizontalGroup(
            panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTransparan6Layout.setVerticalGroup(
            panelTransparan6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan6Layout.createSequentialGroup()
                .addComponent(panelTransparan7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTransparan12.setAlpha(70);

        label14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label14.setText("III. KETERANGAN PETUGAS"); // NOI18N
        label14.setFont(new java.awt.Font("Tahoma", 1, 12));

        javax.swing.GroupLayout panelTransparan12Layout = new javax.swing.GroupLayout(panelTransparan12);
        panelTransparan12.setLayout(panelTransparan12Layout);
        panelTransparan12Layout.setHorizontalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label14, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTransparan12Layout.setVerticalGroup(
            panelTransparan12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p1.setAlpha(50);

        label15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label15.setText("PENCACAH"); // NOI18N
        label15.setFont(new java.awt.Font("Tahoma", 0, 12));

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label15, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        p2.setAlpha(50);

        label16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label16.setText("KORTIM"); // NOI18N
        label16.setFont(new java.awt.Font("Tahoma", 0, 12));

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label16, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        label17.setText("1. Nama Pencacah :"); // NOI18N

        txtB3R1.setCharType(2);
        txtB3R1.setLength(35);

        javax.swing.GroupLayout panelTransparan15Layout = new javax.swing.GroupLayout(panelTransparan15);
        panelTransparan15.setLayout(panelTransparan15Layout);
        panelTransparan15Layout.setHorizontalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(txtB3R1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan15Layout.setVerticalGroup(
            panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB3R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label18.setText("2. NIM :"); // NOI18N

        txtB3R2.setCharType(1);

        javax.swing.GroupLayout panelTransparan16Layout = new javax.swing.GroupLayout(panelTransparan16);
        panelTransparan16.setLayout(panelTransparan16Layout);
        panelTransparan16Layout.setHorizontalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(txtB3R2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan16Layout.setVerticalGroup(
            panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB3R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label19.setText("3. Tanggal Pencacahan :"); // NOI18N

        txtB3R3.setCharType(1);

        javax.swing.GroupLayout panelTransparan17Layout = new javax.swing.GroupLayout(panelTransparan17);
        panelTransparan17.setLayout(panelTransparan17Layout);
        panelTransparan17Layout.setHorizontalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(txtB3R3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan17Layout.setVerticalGroup(
            panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB3R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label20.setText("4. Tanda Tangan :"); // NOI18N

        javax.swing.GroupLayout panelTransparan22Layout = new javax.swing.GroupLayout(panelTransparan22);
        panelTransparan22.setLayout(panelTransparan22Layout);
        panelTransparan22Layout.setHorizontalGroup(
            panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        panelTransparan22Layout.setVerticalGroup(
            panelTransparan22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan22Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        label21.setText("5. Nama Kortim :"); // NOI18N

        txtB3R5.setCharType(2);
        txtB3R5.setLength(35);

        javax.swing.GroupLayout panelTransparan18Layout = new javax.swing.GroupLayout(panelTransparan18);
        panelTransparan18.setLayout(panelTransparan18Layout);
        panelTransparan18Layout.setHorizontalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(txtB3R5, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan18Layout.setVerticalGroup(
            panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan18Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB3R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label22.setText("6. NIM :"); // NOI18N

        txtB3R6.setCharType(1);

        javax.swing.GroupLayout panelTransparan19Layout = new javax.swing.GroupLayout(panelTransparan19);
        panelTransparan19.setLayout(panelTransparan19Layout);
        panelTransparan19Layout.setHorizontalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(txtB3R6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan19Layout.setVerticalGroup(
            panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB3R6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label23.setText("7. Tanggal Pemeriksaan :"); // NOI18N

        txtB3R7.setCharType(1);

        javax.swing.GroupLayout panelTransparan20Layout = new javax.swing.GroupLayout(panelTransparan20);
        panelTransparan20.setLayout(panelTransparan20Layout);
        panelTransparan20Layout.setHorizontalGroup(
            panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(txtB3R7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelTransparan20Layout.setVerticalGroup(
            panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTransparan20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB3R7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label24.setText("8. Tanda Tangan :"); // NOI18N

        javax.swing.GroupLayout panelTransparan23Layout = new javax.swing.GroupLayout(panelTransparan23);
        panelTransparan23.setLayout(panelTransparan23Layout);
        panelTransparan23Layout.setHorizontalGroup(
            panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );
        panelTransparan23Layout.setVerticalGroup(
            panelTransparan23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransparan23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout panelTransparan11Layout = new javax.swing.GroupLayout(panelTransparan11);
        panelTransparan11.setLayout(panelTransparan11Layout);
        panelTransparan11Layout.setHorizontalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addComponent(panelTransparan15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addComponent(panelTransparan16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addComponent(panelTransparan17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addComponent(panelTransparan22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTransparan11Layout.setVerticalGroup(
            panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransparan11Layout.createSequentialGroup()
                .addComponent(panelTransparan12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(p2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelTransparan11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTransparan22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelTabelLayout = new javax.swing.GroupLayout(panelTabel);
        panelTabel.setLayout(panelTabelLayout);
        panelTabelLayout.setHorizontalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTransparan11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTabelLayout.setVerticalGroup(
            panelTabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTabelLayout.createSequentialGroup()
                .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelTransparan11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelScrollLayout = new javax.swing.GroupLayout(panelScroll);
        panelScroll.setLayout(panelScrollLayout);
        panelScrollLayout.setHorizontalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelScrollLayout.setVerticalGroup(
            panelScrollLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelScrollLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        scroolPane1.setViewportView(panelScroll);

        add(scroolPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtB1R6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtB1R6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_txtB1R6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.Label label1;
    private pkl49.component.Label label10;
    private pkl49.component.Label label11;
    private pkl49.component.Label label12;
    private pkl49.component.Label label13;
    private pkl49.component.Label label14;
    private pkl49.component.Label label15;
    private pkl49.component.Label label16;
    private pkl49.component.Label label17;
    private pkl49.component.Label label18;
    private pkl49.component.Label label19;
    private pkl49.component.Label label20;
    private pkl49.component.Label label21;
    private pkl49.component.Label label22;
    private pkl49.component.Label label23;
    private pkl49.component.Label label24;
    private pkl49.component.Label label25;
    private pkl49.component.Label label26;
    private pkl49.component.Label label27;
    private pkl49.component.Label label31;
    private pkl49.component.Label label32;
    private pkl49.component.Label label33;
    private pkl49.component.Label label34;
    private pkl49.component.Label label35;
    private pkl49.component.Label label36;
    private pkl49.component.Label label37;
    private pkl49.component.Label label9;
    private pkl49.component.Label labelDesa;
    private pkl49.component.Label labelKab;
    private pkl49.component.Label labelKec;
    private pkl49.component.LabelWaktu labelWaktu1;
    private pkl49.component.PanelTransparan p1;
    private pkl49.component.PanelTransparan p2;
    private pkl49.component.PanelTransparan panelScroll;
    private pkl49.component.PanelTransparan panelTabel;
    private pkl49.component.PanelTransparan panelTransparan1;
    private pkl49.component.PanelTransparan panelTransparan10;
    private pkl49.component.PanelTransparan panelTransparan11;
    private pkl49.component.PanelTransparan panelTransparan12;
    private pkl49.component.PanelTransparan panelTransparan13;
    private pkl49.component.PanelTransparan panelTransparan14;
    private pkl49.component.PanelTransparan panelTransparan15;
    private pkl49.component.PanelTransparan panelTransparan16;
    private pkl49.component.PanelTransparan panelTransparan17;
    private pkl49.component.PanelTransparan panelTransparan18;
    private pkl49.component.PanelTransparan panelTransparan19;
    private pkl49.component.PanelTransparan panelTransparan2;
    private pkl49.component.PanelTransparan panelTransparan20;
    private pkl49.component.PanelTransparan panelTransparan21;
    private pkl49.component.PanelTransparan panelTransparan22;
    private pkl49.component.PanelTransparan panelTransparan23;
    private pkl49.component.PanelTransparan panelTransparan24;
    private pkl49.component.PanelTransparan panelTransparan25;
    private pkl49.component.PanelTransparan panelTransparan26;
    private pkl49.component.PanelTransparan panelTransparan27;
    private pkl49.component.PanelTransparan panelTransparan28;
    private pkl49.component.PanelTransparan panelTransparan29;
    private pkl49.component.PanelTransparan panelTransparan30;
    private pkl49.component.PanelTransparan panelTransparan4;
    private pkl49.component.PanelTransparan panelTransparan5;
    private pkl49.component.PanelTransparan panelTransparan6;
    private pkl49.component.PanelTransparan panelTransparan7;
    private pkl49.component.PanelTransparan panelTransparan8;
    private pkl49.component.PanelTransparan panelTransparan9;
    private pkl49.component.ScroolPane scroolPane1;
    private pkl49.component.TextField txtB1R1;
    private pkl49.component.TextField txtB1R2;
    private pkl49.component.TextField txtB1R3;
    private pkl49.component.TextField txtB1R4;
    private pkl49.component.TextField txtB1R5;
    private pkl49.component.TextField txtB1R6;
    private pkl49.component.TextField txtB1R7;
    private pkl49.component.TextField txtB1R8;
    private pkl49.component.TextField txtB1R9;
    private pkl49.component.TextField txtB2R1;
    private pkl49.component.TextField txtB2R2;
    private pkl49.component.TextField txtB2R3;
    private pkl49.component.TextField txtB2R4;
    private pkl49.component.TextField txtB2R5;
    private pkl49.component.TextField txtB2R6;
    private pkl49.component.TextField txtB3R1;
    private pkl49.component.TextField txtB3R2;
    private pkl49.component.TextField txtB3R3;
    private pkl49.component.TextField txtB3R5;
    private pkl49.component.TextField txtB3R6;
    private pkl49.component.TextField txtB3R7;
    // End of variables declaration//GEN-END:variables

}
