/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Utama.java
 *
 * Created on Feb 11, 2010, 12:34:37 AM
 */

package pkl49.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import pkl49.component.GlassPane;
import pkl49.component.PanelImage1;
import pkl49.component.PanelTransparan;
import pkl49.control.ControlMenu;
import pkl49.control.Controller;
import pkl49.control.FormUtil;
import pkl49.util.transfer.Ekspor;

/**
 *
 * @author Mr.Hands
 */
public class MainMenu extends javax.swing.JPanel {

    private FormUtama main;
    /** Creates new form Utama */
    public MainMenu() {
        initComponents();
    }

    public void setMain(FormUtama main) {
        this.main = main;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        horizontalCaret1 = new pkl49.component.HorizontalCaret();
        PanelInduk = new pkl49.component.PanelTransparan();
        PanelTwoChoice = new pkl49.component.PanelTransparan();
        bigButton7 = new pkl49.component.BigButton();
        bigButton8 = new pkl49.component.BigButton();
        PanelPodes = new pkl49.component.PanelTransparan();
        bigButton2 = new pkl49.component.BigButton();
        bigButton4 = new pkl49.component.BigButton();
        panelRT = new pkl49.component.PanelTransparan();
        btnUpdateRT = new pkl49.component.BigButton();
        btnInsertRT = new pkl49.component.BigButton();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        PanelInduk.setBorder(null);
        PanelInduk.setLayout(new java.awt.CardLayout());

        PanelTwoChoice.setBorder(null);
        PanelTwoChoice.setLayout(new java.awt.GridBagLayout());

        bigButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/PODES_1.png"))); // NOI18N
        bigButton7.setToolTipText("Klik untuk masuk ke menu entry podes");
        bigButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        PanelTwoChoice.add(bigButton7, gridBagConstraints);

        bigButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/RT.png"))); // NOI18N
        bigButton8.setToolTipText("Klik untuk masuk ke menu entry RT");
        bigButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigButton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        PanelTwoChoice.add(bigButton8, gridBagConstraints);

        PanelInduk.add(PanelTwoChoice, "paneltwochoice");

        PanelPodes.setBorder(null);
        PanelPodes.setLayout(new java.awt.GridBagLayout());

        bigButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/pODES.png"))); // NOI18N
        bigButton2.setToolTipText("Klik untuk mengentry data podes");
        bigButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        PanelPodes.add(bigButton2, gridBagConstraints);

        bigButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/updatepodes.png"))); // NOI18N
        bigButton4.setToolTipText("Klik untuk mengedit data podes");
        bigButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigButton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        PanelPodes.add(bigButton4, gridBagConstraints);

        PanelInduk.add(PanelPodes, "panelpodes");

        panelRT.setBorder(null);
        panelRT.setLayout(new java.awt.GridBagLayout());

        btnUpdateRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/updateRT.png"))); // NOI18N
        btnUpdateRT.setToolTipText("Klik untuk mengedit data rumah tangga");
        btnUpdateRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateRTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelRT.add(btnUpdateRT, gridBagConstraints);

        btnInsertRT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/ENTRI RT.png"))); // NOI18N
        btnInsertRT.setToolTipText("Klik untuk mengedit data rumah tangga");
        btnInsertRT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertRTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 10);
        panelRT.add(btnInsertRT, gridBagConstraints);

        PanelInduk.add(panelRT, "panelrt");

        add(PanelInduk, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void bigButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigButton2ActionPerformed
        ControlMenu.entryPodes(main);
    }//GEN-LAST:event_bigButton2ActionPerformed

    private void btnInsertRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertRTActionPerformed
        ControlMenu.entryRT(main);
    }//GEN-LAST:event_btnInsertRTActionPerformed

    private void bigButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigButton7ActionPerformed
        // TODO add your handling code here:
        showPanelMenu(PanelPodes, "panelpodes");
    }//GEN-LAST:event_bigButton7ActionPerformed

    private void bigButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigButton8ActionPerformed
       
        showPanelMenu(panelRT, "panelrt");
    }//GEN-LAST:event_bigButton8ActionPerformed

    private void btnUpdateRTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateRTActionPerformed
        ControlMenu.updateRT(main);
    }//GEN-LAST:event_btnUpdateRTActionPerformed

    private void bigButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigButton4ActionPerformed
        ControlMenu.updatePodes(main);
    }//GEN-LAST:event_bigButton4ActionPerformed
/* * Menampilkan panel pada cardLayout
     * @param panel
     * @param nama
     * @param induk
     */
     protected  void showPanel(Component panel, String nama){
        if (panel.isVisible()){
            return;
        }
        ((CardLayout)main.getPanelGradient1().getLayout()).show(main.getPanelGradient1(), nama);
    }

    protected  void showPanel2(Component panel, String nama){
        if (panel.isVisible()){
            return;
        }
//        ((CardLayout)main.getPanelKuesioner1().getPanelInduk().getLayout()).show(main.getPanelKuesioner1().getPanelInduk(), nama);
    }
    public PanelTransparan getPanelInduk() {
        return PanelInduk;
    }

    public PanelTransparan getPanelTwoChoice() {
        return PanelTwoChoice;
    }

     protected  void showPanelMenu(Component panel, String nama){
        if (panel.isVisible()){
            return;
        }
        ((CardLayout)PanelInduk.getLayout()).show(PanelInduk, nama);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.PanelTransparan PanelInduk;
    private pkl49.component.PanelTransparan PanelPodes;
    private pkl49.component.PanelTransparan PanelTwoChoice;
    private pkl49.component.BigButton bigButton2;
    private pkl49.component.BigButton bigButton4;
    private pkl49.component.BigButton bigButton7;
    private pkl49.component.BigButton bigButton8;
    private pkl49.component.BigButton btnInsertRT;
    private pkl49.component.BigButton btnUpdateRT;
    private pkl49.component.HorizontalCaret horizontalCaret1;
    private pkl49.component.PanelTransparan panelRT;
    // End of variables declaration//GEN-END:variables

}
