/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelInput.java
 *
 * Created on Feb 10, 2010, 9:46:39 PM
 */

package pkl49.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.interpolation.KeyFrames;
import org.jdesktop.animation.timing.interpolation.KeyTimes;
import org.jdesktop.animation.timing.interpolation.KeyValues;
import org.jdesktop.animation.timing.interpolation.PropertySetter;
import pkl49.control.Controller;

/**
 *
 * @author Kean
 */
public class PanelProgressAnimasi extends javax.swing.JPanel{

    private int slide;
    private Image[] image;
    private Animator animasi;

    private PanelKuesioner kuesioner;
    /**Sebagai penanda untuk proses yang akan dikerjakan*/
    private String key;
    /**Menunjukan status dari suatu proses. Berhasil = 1, Gagal = 0*/
    private int status;

    /** Creates new form PanelInput */
    public PanelProgressAnimasi() {
        initComponents();
        setOpaque(false);
        image = new Image[10];
        for(int i = 0;i<image.length;i++){
            image[i] = new ImageIcon(getClass().getResource("/pkl49/image/update"+(i+1)+".png")).getImage();
        }

        addMouseListener(new MouseListener() {

            public void mouseClicked(MouseEvent e) {
            }

            public void mousePressed(MouseEvent e) {
            }

            public void mouseReleased(MouseEvent e) {
            }

            public void mouseEntered(MouseEvent e) {
            }

            public void mouseExited(MouseEvent e) {
            }
        });
        addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }

            @Override
            public void keyTyped(KeyEvent e) {
            }

        });
start();
    }

    public int getSlide() {
        return slide;
    }

    /**
     * Menentukan index dari gambar
     * @param slide
     */
    public void setSlide(int slide) {
        this.slide = slide;
        repaint();
    }


    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public PanelKuesioner getKuesioner() {
        return kuesioner;
    }

    public void setKuesioner(PanelKuesioner kuesioner) {
        this.kuesioner = kuesioner;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D gd = (Graphics2D) g.create();
        int w = getWidth();
        int h = getHeight();
        int x = (w-image[getSlide()].getWidth(null))/2;
        int y = (h-image[getSlide()].getHeight(null))/2;
        gd.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        if(animasi.isRunning()){
            gd.setColor(new Color(1f, 1f, 1f, 0.5f));
            gd.fillRect(0, 0, w, h);
            gd.drawImage(image[getSlide()], x, y, null);
            gd.dispose();            
        }else{
            gd.setColor(new Color(1f, 1f, 1f, 0.5f));
            gd.fillRect(0, 0, w, h);
            gd.drawImage(image[0], x, y, null);
            gd.dispose();
        }
    }

    private void setUpAnimation(){
        KeyValues keyValues = KeyValues.create(0,1,2,3,4,5,6,7,8,9);
        KeyTimes keyTimes = new KeyTimes(0f,0.1f,0.2f,0.3f,0.4f,0.55f,0.6f,0.7f,0.85f,1f);
        KeyFrames keyFrames = new KeyFrames(keyValues, keyTimes);
        animasi = new Animator(500);
        animasi.addTarget(new PropertySetter(this, "slide", keyFrames));
        animasi.setRepeatCount(100);
        animasi.setRepeatBehavior(Animator.RepeatBehavior.LOOP);
  }

    public void start(){
        setUpAnimation();
        setSlide(0);
        animasi.start();
    }

    public void execute(){
        Task task = new Task();
        task.execute();
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    class Task extends SwingWorker<Object, Object>{

        @Override
        protected Object doInBackground() throws Exception {
            proses();
            return null;
        }

        @Override
        protected void done() {
            selesai();
        }
    }

    private void proses(){
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(key.equals("simpan")){
            status = Controller.simpanKuesioner(kuesioner);
        }else if(key.equals("update")){
            status = Controller.simpanKuesioner(kuesioner);
        }
    }
    private void selesai(){
        setVisible(false);
        Toolkit.getDefaultToolkit().beep();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        if(key.equals("simpan")){
            if(status == 1){
                JOptionPane.showMessageDialog(kuesioner, "Data berhasil disimpan!");
            }else{
                JOptionPane.showMessageDialog(kuesioner, "Data gagal disimpan!");
            }
        }else if(key.equals("update")){
            if(status == 1){
                JOptionPane.showMessageDialog(kuesioner, "Data berhasil diupdate!");
            }else{
                JOptionPane.showMessageDialog(kuesioner, "Data gagal diupdate!");
            }
        }

    }

}
