/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelInput.java
 *
 * Created on Feb 10, 2010, 9:46:39 PM
 */

package pkl49.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import pkl49.control.Controller;

/**
 *
 * @author Kean
 */
public class PanelProgress extends javax.swing.JPanel{

    
    private PanelKuesioner kuesioner;
    /**Sebagai penanda untuk proses yang akan dikerjakan*/
    private String key;
    /**Menunjukan status dari suatu proses. Berhasil = 1, Gagal = 0*/
    private int status;

    /** Creates new form PanelInput */
    public PanelProgress() {
        initComponents();
        setOpaque(false);

        addMouseListener(new MouseListener() {

            public void mouseClicked(MouseEvent e) {
            }

            public void mousePressed(MouseEvent e) {
            }

            public void mouseReleased(MouseEvent e) {
            }

            public void mouseEntered(MouseEvent e) {
            }

            public void mouseExited(MouseEvent e) {
            }
        });
        addKeyListener(new KeyAdapter() {

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }

            @Override
            public void keyTyped(KeyEvent e) {
            }

        });
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public PanelKuesioner getKuesioner() {
        return kuesioner;
    }

    public void setKuesioner(PanelKuesioner kuesioner) {
        this.kuesioner = kuesioner;
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressBar = new javax.swing.JProgressBar();

        setLayout(new java.awt.GridBagLayout());

        progressBar.setIndeterminate(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 255;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(140, 59, 141, 76);
        add(progressBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D gd = (Graphics2D) g.create();
        int w = getWidth();
        int h = getHeight();
        gd.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        gd.setColor(new Color(1f, 1f, 1f, 0.6f));
        gd.fillRect(0, 0, w, h);
        gd.dispose();
        
    }

    public void execute(){
        Task task = new Task();
        task.execute();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables

    class Task extends SwingWorker<Object, Object>{

        @Override
        protected Object doInBackground() throws Exception {
            proses();
            return null;
        }

        @Override
        protected void done() {
            selesai();
        }
    }

    private void proses(){
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if(key.equals("simpan")){
            System.out.println("Status=");
            status = Controller.simpanKuesioner(kuesioner);
            System.out.println("Status="+status);
        }else if(key.equals("update")){
            status = Controller.update(kuesioner);
        }
    }
    private void selesai(){
        setVisible(false);
        Toolkit.getDefaultToolkit().beep();
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        if(key.equals("simpan")){
            if(status==1){
                JOptionPane.showMessageDialog(kuesioner, "Data berhasil disimpan!");
            }else if(status==0){
                JOptionPane.showMessageDialog(kuesioner, "Data gagal disimpan!");
            }
        }else if(key.equals("update")){
            if(status == 1){
                JOptionPane.showMessageDialog(kuesioner, "Data berhasil diupdate!");
            }else{
                JOptionPane.showMessageDialog(kuesioner, "Data gagal diupdate!");
            }
        }

    }

}
