/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Blok8B.java
 *
 * Created on 12 Jan 10, 0:13:05
 */

package pkl49.view;

import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import pkl49.component.ButtonGloss;
import pkl49.component.PanelTransparan;
import pkl49.component.TextField;
import pkl49.control.Controller;
import pkl49.validasi.ValidasiBlok7A;
import pkl49.validasi.ValidasiBlok7B;
import pkl49.validasi.ValidasiBlok8A;
import pkl49.validasi.ValidasiHalaman1_2;


/**
 *
 * @author Ken
 */
public class PanelKuesioner extends javax.swing.JPanel{


    private List<Halaman3> listHal3;
    private List<Halaman8> listHal8;
    private List<Halaman9> listHal9;
    private List<String> namaHal3;
    private List<String> namaHal8;
    private List<String> namaHal9;
    private FormUtama formUtama;
    /** Creates new form Blok8B */
    public PanelKuesioner() {
        initComponents();
        setListHal();
    }

    public List<Halaman8> getListHal8() {
        return listHal8;
    }

    public List<Halaman9> getListHal9() {
        return listHal9;
    }

    public List<String> getNamaHal8() {
        return namaHal8;
    }

    public List<String> getNamaHal9() {
        return namaHal9;
    }

    public List<Halaman3> getListHal3() {
        return listHal3;
    }

    public PanelTransparan getPanelInduk() {
        return panelInduk;
    }

    public ButtonGloss getBtnSimpan() {
        return btnSimpan;
    }

    public Halaman1 getHalaman1() {
        return halaman1;
    }

    public Halaman2 getHalaman2() {
        return halaman2;
    }

    public Halaman3 getHalaman3_1() {
        return halaman3_1;
    }

    public Halaman3 getHalaman3_10() {
        return halaman3_10;
    }

    public Halaman3 getHalaman3_11() {
        return halaman3_11;
    }

    public Halaman3 getHalaman3_12() {
        return halaman3_12;
    }

    public Halaman3 getHalaman3_13() {
        return halaman3_13;
    }

    public Halaman3 getHalaman3_14() {
        return halaman3_14;
    }

    public Halaman3 getHalaman3_15() {
        return halaman3_15;
    }

    public Halaman3 getHalaman3_16() {
        return halaman3_16;
    }

    public Halaman3 getHalaman3_17() {
        return halaman3_17;
    }

    public Halaman3 getHalaman3_18() {
        return halaman3_18;
    }

    public Halaman3 getHalaman3_19() {
        return halaman3_19;
    }

    public Halaman3 getHalaman3_2() {
        return halaman3_2;
    }

    public Halaman3 getHalaman3_20() {
        return halaman3_20;
    }

    public Halaman3 getHalaman3_21() {
        return halaman3_21;
    }

    public Halaman3 getHalaman3_22() {
        return halaman3_22;
    }

    public Halaman3 getHalaman3_23() {
        return halaman3_23;
    }

    public Halaman3 getHalaman3_24() {
        return halaman3_24;
    }

    public Halaman3 getHalaman3_25() {
        return halaman3_25;
    }

    public Halaman3 getHalaman3_3() {
        return halaman3_3;
    }

    public Halaman3 getHalaman3_4() {
        return halaman3_4;
    }

    public Halaman3 getHalaman3_5() {
        return halaman3_5;
    }

    public Halaman3 getHalaman3_6() {
        return halaman3_6;
    }

    public Halaman3 getHalaman3_7() {
        return halaman3_7;
    }

    public Halaman3 getHalaman3_8() {
        return halaman3_8;
    }

    public Halaman3 getHalaman3_9() {
        return halaman3_9;
    }

    public Halaman4 getHalaman4() {
        return halaman4;
    }

    public Halaman5 getHalaman5() {
        return halaman5;
    }

    public Halaman6 getHalaman6() {
        return halaman6;
    }

    public Halaman7 getHalaman7() {
        return halaman7;
    }

    public Halaman8 getHalaman8() {
        return halaman8_1;
    }

    public Halaman9 getHalaman9() {
        return halaman9_1;
    }

    public void setFormUtama(FormUtama formUtama) {
        this.formUtama = formUtama;
        setValidasi();
    }





    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelInduk = new pkl49.component.PanelTransparan();
        halaman1 = new pkl49.view.Halaman1();
        halaman5 = new pkl49.view.Halaman5();
        halaman6 = new pkl49.view.Halaman6();
        halaman2 = new pkl49.view.Halaman2();
        halaman3_1 = new pkl49.view.Halaman3();
        halaman3_2 = new pkl49.view.Halaman3();
        halaman3_3 = new pkl49.view.Halaman3();
        halaman3_4 = new pkl49.view.Halaman3();
        halaman3_5 = new pkl49.view.Halaman3();
        halaman3_6 = new pkl49.view.Halaman3();
        halaman3_7 = new pkl49.view.Halaman3();
        halaman3_8 = new pkl49.view.Halaman3();
        halaman3_9 = new pkl49.view.Halaman3();
        halaman3_10 = new pkl49.view.Halaman3();
        halaman3_11 = new pkl49.view.Halaman3();
        halaman3_12 = new pkl49.view.Halaman3();
        halaman3_13 = new pkl49.view.Halaman3();
        halaman3_14 = new pkl49.view.Halaman3();
        halaman3_15 = new pkl49.view.Halaman3();
        halaman3_16 = new pkl49.view.Halaman3();
        halaman3_17 = new pkl49.view.Halaman3();
        halaman3_18 = new pkl49.view.Halaman3();
        halaman3_19 = new pkl49.view.Halaman3();
        halaman3_20 = new pkl49.view.Halaman3();
        halaman3_21 = new pkl49.view.Halaman3();
        halaman3_22 = new pkl49.view.Halaman3();
        halaman3_23 = new pkl49.view.Halaman3();
        halaman3_24 = new pkl49.view.Halaman3();
        halaman3_25 = new pkl49.view.Halaman3();
        halaman4 = new pkl49.view.Halaman4();
        halaman7 = new pkl49.view.Halaman7();
        halaman8_1 = new pkl49.view.Halaman8();
        halaman8_2 = new pkl49.view.Halaman8();
        halaman8_3 = new pkl49.view.Halaman8();
        halaman8_4 = new pkl49.view.Halaman8();
        halaman9_1 = new pkl49.view.Halaman9();
        halaman9_2 = new pkl49.view.Halaman9();
        halaman9_3 = new pkl49.view.Halaman9();
        halaman9_4 = new pkl49.view.Halaman9();
        halaman9_5 = new pkl49.view.Halaman9();
        halaman8_5 = new pkl49.view.Halaman8();
        halaman8_6 = new pkl49.view.Halaman8();
        halaman8_7 = new pkl49.view.Halaman8();
        halaman8_8 = new pkl49.view.Halaman8();
        halaman8_9 = new pkl49.view.Halaman8();
        halaman8_10 = new pkl49.view.Halaman8();
        panelTransparan1 = new pkl49.component.PanelTransparan();
        btnPrev = new pkl49.component.ButtonGlass();
        btnNext = new pkl49.component.ButtonGlass();
        panelTransparan2 = new pkl49.component.PanelTransparan();
        btnSimpan = new pkl49.component.ButtonGloss();

        setOpaque(false);

        panelInduk.setBorder(null);
        panelInduk.setLayout(new java.awt.CardLayout());
        panelInduk.add(halaman1, "Halaman1");
        panelInduk.add(halaman5, "Halaman5");
        panelInduk.add(halaman6, "Halaman6");
        panelInduk.add(halaman2, "Halaman2");
        panelInduk.add(halaman3_1, "Halaman3_1");
        panelInduk.add(halaman3_2, "Halaman3_2");
        panelInduk.add(halaman3_3, "Halaman3_3");
        panelInduk.add(halaman3_4, "Halaman3_4");
        panelInduk.add(halaman3_5, "Halaman3_5");
        panelInduk.add(halaman3_6, "Halaman3_6");
        panelInduk.add(halaman3_7, "Halaman3_7");
        panelInduk.add(halaman3_8, "Halaman3_8");
        panelInduk.add(halaman3_9, "Halaman3_9");
        panelInduk.add(halaman3_10, "Halaman3_10");
        panelInduk.add(halaman3_11, "Halaman3_11");
        panelInduk.add(halaman3_12, "Halaman3_12");
        panelInduk.add(halaman3_13, "Halaman3_13");
        panelInduk.add(halaman3_14, "Halaman3_14");
        panelInduk.add(halaman3_15, "Halaman3_15");
        panelInduk.add(halaman3_16, "Halaman3_16");
        panelInduk.add(halaman3_17, "Halaman3_17");
        panelInduk.add(halaman3_18, "Halaman3_18");
        panelInduk.add(halaman3_19, "Halaman3_19");
        panelInduk.add(halaman3_20, "Halaman3_20");
        panelInduk.add(halaman3_21, "Halaman3_21");
        panelInduk.add(halaman3_22, "Halaman3_22");
        panelInduk.add(halaman3_23, "Halaman3_23");
        panelInduk.add(halaman3_24, "Halaman3_24");
        panelInduk.add(halaman3_25, "Halaman3_25");
        panelInduk.add(halaman4, "Halaman4");
        panelInduk.add(halaman7, "Halaman7");
        panelInduk.add(halaman8_1, "Halaman8_1");
        panelInduk.add(halaman8_2, "Halaman8_2");
        panelInduk.add(halaman8_3, "Halaman8_3");
        panelInduk.add(halaman8_4, "Halaman8_4");
        panelInduk.add(halaman9_1, "Halaman9_1");
        panelInduk.add(halaman9_2, "Halaman9_2");
        panelInduk.add(halaman9_3, "Halaman9_3");
        panelInduk.add(halaman9_4, "Halaman9_4");
        panelInduk.add(halaman9_5, "Halaman9_5");
        panelInduk.add(halaman8_5, "Halaman8_5");
        panelInduk.add(halaman8_6, "Halaman8_6");
        panelInduk.add(halaman8_7, "Halaman8_7");
        panelInduk.add(halaman8_8, "Halaman8_8");
        panelInduk.add(halaman8_9, "Halaman8_9");
        panelInduk.add(halaman8_10, "Halaman8_10");

        panelTransparan1.setBorder(null);
        panelTransparan1.setLayout(new java.awt.GridBagLayout());

        btnPrev.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/1leftarrow32.png"))); // NOI18N
        btnPrev.setToolTipText("Halaman sebelumnya");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelTransparan1.add(btnPrev, gridBagConstraints);

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkl49/image/1rightarrow32.png"))); // NOI18N
        btnNext.setToolTipText("Halaman selanjutnya");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = -20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        panelTransparan1.add(btnNext, gridBagConstraints);

        panelTransparan2.setBorder(null);
        panelTransparan2.setLayout(new java.awt.GridBagLayout());

        btnSimpan.setText("Save");
        btnSimpan.setEnabled(false);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        panelTransparan2.add(btnSimpan, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelTransparan1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTransparan2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(panelInduk, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelInduk, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelTransparan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTransparan1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if(evt.getActionCommand().equals("Save")){
            Controller.showProgress(formUtama, this, "simpan");
//            Controller.simpanKuesioner(this);
        }else{
            Controller.showProgress(formUtama, this, "update");
//            Controller.update(this);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        Controller.backward(this);
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

        Controller.forward(this);
    }//GEN-LAST:event_btnNextActionPerformed
//    protected  void showPanel(Component panel, String nama){
//        if (panel.isVisible()){
//            return;
//        }
//        ((CardLayout)formUtama.getHome().getPanelInduk().getLayout()).show(formUtama.getHome().getPanelInduk(), nama);
//    }
protected  void showPanel2(Component panel, String nama){
        if (panel.isVisible()){
            return;
        }
        ((CardLayout)formUtama.getPanelGradient1().getLayout()).show(formUtama.getPanelGradient1(), nama);
    }


//    protected  void showPanel(Component panel, String nama){
//        if (panel.isVisible()){
//            return;
//        }
//        ((CardLayout)formUtama.getPanelGradient1().getLayout()).show(formUtama.getPanelGradient1(), nama);
//    }
    private void setListHal(){
        listHal3 = new ArrayList<Halaman3>();
        listHal3.add(halaman3_1);
        listHal3.add(halaman3_2);
        listHal3.add(halaman3_3);
        listHal3.add(halaman3_4);
        listHal3.add(halaman3_5);
        listHal3.add(halaman3_6);
        listHal3.add(halaman3_7);
        listHal3.add(halaman3_8);
        listHal3.add(halaman3_9);
        listHal3.add(halaman3_10);
        listHal3.add(halaman3_11);
        listHal3.add(halaman3_12);
        listHal3.add(halaman3_13);
        listHal3.add(halaman3_14);
        listHal3.add(halaman3_15);
        listHal3.add(halaman3_16);
        listHal3.add(halaman3_17);
        listHal3.add(halaman3_18);
        listHal3.add(halaman3_19);
        listHal3.add(halaman3_20);
        listHal3.add(halaman3_21);
        listHal3.add(halaman3_22);
        listHal3.add(halaman3_23);
        listHal3.add(halaman3_24);
        listHal3.add(halaman3_25);
    

        listHal8 = new ArrayList<Halaman8>();
        listHal8.add(halaman8_1);
        listHal8.add(halaman8_2);
        listHal8.add(halaman8_3);
        listHal8.add(halaman8_4);
        listHal8.add(halaman8_5);
        listHal8.add(halaman8_6);
        listHal8.add(halaman8_7);
        listHal8.add(halaman8_8);
        listHal8.add(halaman8_9);
        listHal8.add(halaman8_10);

        namaHal3 =new ArrayList<String>();
        namaHal3.add("Halaman3_1");
        namaHal3.add("Halaman3_2");
        namaHal3.add("Halaman3_3");
        namaHal3.add("Halaman3_4");
        namaHal3.add("Halaman3_5");
        namaHal3.add("Halaman3_6");
        namaHal3.add("Halaman3_7");
        namaHal3.add("Halaman3_8");
        namaHal3.add("Halaman3_9");
        namaHal3.add("Halaman3_10");

        namaHal8 =new ArrayList<String>();
        namaHal8.add("Halaman8_1");
        namaHal8.add("Halaman8_2");
        namaHal8.add("Halaman8_3");
        namaHal8.add("Halaman8_4");

        for(int i=0;i<listHal8.size();i++){
            listHal8.get(i).setKuesioner(this);
        }


        listHal9= new ArrayList<Halaman9>();
        listHal9.add(halaman9_1);
        listHal9.add(halaman9_2);
        listHal9.add(halaman9_3);
        listHal9.add(halaman9_4);
        listHal9.add(halaman9_5);

        namaHal9 =new ArrayList<String>();
        namaHal9.add("Halaman9_1");
        namaHal9.add("Halaman9_2");
        namaHal9.add("Halaman9_3");
        namaHal9.add("Halaman9_4");
        namaHal9.add("Halaman9_5");
        for(int i=0;i<listHal9.size();i++){
            listHal9.get(i).setKuesioner(this);
        }
    }

    private void setValidasi(){
        ValidasiHalaman1_2 val1 = new ValidasiHalaman1_2(halaman1.getListHalaman1(), "Hal1", this);
        ValidasiHalaman1_2 val2 = new ValidasiHalaman1_2("Hal2",halaman2.getListHalaman2(), this);
        ValidasiBlok7A valB7A = new ValidasiBlok7A(this, halaman5.getListBlok7A());
        ValidasiBlok7B valB7B = new ValidasiBlok7B(this, halaman6.getListBlok7B());
        ValidasiBlok8A valB8A1 = new ValidasiBlok8A(formUtama,this, halaman7.getListBlok8AKol2(), ValidasiBlok8A.KOLOM2);
        ValidasiBlok8A valB8A2 = new ValidasiBlok8A(formUtama,this, halaman7.getListBaris26(),ValidasiBlok8A.BARIS26);
        ValidasiBlok8A valB8A3 = new ValidasiBlok8A(formUtama,this, ValidasiBlok8A.KOLOM5, halaman7.getListBlok8AKol5());
        ValidasiBlok8A valB8A4 = new ValidasiBlok8A(formUtama,this,  ValidasiBlok8A.KOLOM13,halaman7.getListBlok8AKol13());
        for(int i=0;i<25;i++)
            listHal3.get(i).setKues(this);
        halaman4.setKues(this);

        halaman1.getTxtB1R8().getDocument().addDocumentListener(new DocListener(halaman2.getTxtB4K2_1(),halaman3_1.getListBlok5().get(0)));
        for(int i=0;i<25;i++){
            halaman2.getListHalaman2().get(i).get(0).getDocument().addDocumentListener(new DocListener(getListHal3().get(i).getListBlok5().get(0)));
        }
    }

    private class DocListener implements DocumentListener{

        private TextField textField1;
        private TextField textField2 = null;


        public DocListener(TextField textField1) {
            this.textField1 = textField1;
        }

        public DocListener(TextField textField1, TextField textField2) {
            this.textField1 = textField1;
            this.textField2 = textField2;
        }

        public void insertUpdate(DocumentEvent e) {
            textField1.setDocument(e.getDocument());
            if(textField2!=null){
                textField2.setDocument(e.getDocument());
            }
        }

        public void removeUpdate(DocumentEvent e) {
            textField1.setDocument(e.getDocument());
            if(textField2!=null){
                textField2.setDocument(e.getDocument());
            }
        }

        public void changedUpdate(DocumentEvent e) {
            textField1.setDocument(e.getDocument());
            if(textField2!=null){
                textField2.setDocument(e.getDocument());
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.ButtonGlass btnNext;
    private pkl49.component.ButtonGlass btnPrev;
    private pkl49.component.ButtonGloss btnSimpan;
    private pkl49.view.Halaman1 halaman1;
    private pkl49.view.Halaman2 halaman2;
    private pkl49.view.Halaman3 halaman3_1;
    private pkl49.view.Halaman3 halaman3_10;
    private pkl49.view.Halaman3 halaman3_11;
    private pkl49.view.Halaman3 halaman3_12;
    private pkl49.view.Halaman3 halaman3_13;
    private pkl49.view.Halaman3 halaman3_14;
    private pkl49.view.Halaman3 halaman3_15;
    private pkl49.view.Halaman3 halaman3_16;
    private pkl49.view.Halaman3 halaman3_17;
    private pkl49.view.Halaman3 halaman3_18;
    private pkl49.view.Halaman3 halaman3_19;
    private pkl49.view.Halaman3 halaman3_2;
    private pkl49.view.Halaman3 halaman3_20;
    private pkl49.view.Halaman3 halaman3_21;
    private pkl49.view.Halaman3 halaman3_22;
    private pkl49.view.Halaman3 halaman3_23;
    private pkl49.view.Halaman3 halaman3_24;
    private pkl49.view.Halaman3 halaman3_25;
    private pkl49.view.Halaman3 halaman3_3;
    private pkl49.view.Halaman3 halaman3_4;
    private pkl49.view.Halaman3 halaman3_5;
    private pkl49.view.Halaman3 halaman3_6;
    private pkl49.view.Halaman3 halaman3_7;
    private pkl49.view.Halaman3 halaman3_8;
    private pkl49.view.Halaman3 halaman3_9;
    private pkl49.view.Halaman4 halaman4;
    private pkl49.view.Halaman5 halaman5;
    private pkl49.view.Halaman6 halaman6;
    private pkl49.view.Halaman7 halaman7;
    private pkl49.view.Halaman8 halaman8_1;
    private pkl49.view.Halaman8 halaman8_10;
    private pkl49.view.Halaman8 halaman8_2;
    private pkl49.view.Halaman8 halaman8_3;
    private pkl49.view.Halaman8 halaman8_4;
    private pkl49.view.Halaman8 halaman8_5;
    private pkl49.view.Halaman8 halaman8_6;
    private pkl49.view.Halaman8 halaman8_7;
    private pkl49.view.Halaman8 halaman8_8;
    private pkl49.view.Halaman8 halaman8_9;
    private pkl49.view.Halaman9 halaman9_1;
    private pkl49.view.Halaman9 halaman9_2;
    private pkl49.view.Halaman9 halaman9_3;
    private pkl49.view.Halaman9 halaman9_4;
    private pkl49.view.Halaman9 halaman9_5;
    private pkl49.component.PanelTransparan panelInduk;
    private pkl49.component.PanelTransparan panelTransparan1;
    private pkl49.component.PanelTransparan panelTransparan2;
    // End of variables declaration//GEN-END:variables

}
