/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelInput.java
 *
 * Created on Feb 10, 2010, 9:46:39 PM
 */

package pkl49.view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.JOptionPane;
import pkl49.component.ButtonGloss;
import pkl49.component.Formatter;
import pkl49.component.TextField;
import pkl49.control.Controller;

/**
 *
 * @author Mr.Hands
 */
public class PanelInput extends javax.swing.JPanel implements KeyListener{

    private PanelKuesioner kues;
    private FormUtama formUtama;
    /** Creates new form PanelInput */
    public PanelInput() {
        initComponents();
        txtB1R1.addKeyListener(this);
        txtB1R3.addKeyListener(this);
        txtB1R4.addKeyListener(this);
        txtB1R5.addKeyListener(this);
        txtB1R7.addKeyListener(this);
        Formatter n = new Formatter("###B");
        txtB1R5.setFormatterFactory(n);
        
    }

    public TextField getTxtB1R1() {
        return txtB1R1;
    }



    public void setKues(PanelKuesioner kues) {
        this.kues = kues;
    }

    public void setFormUtama(FormUtama formUtama) {
        this.formUtama = formUtama;
    }


    public ButtonGloss getBtnCancel() {
        return btnCancel;
    }

    public ButtonGloss getBtnOK() {
        return btnOK;
    }

    public String getNKS(){
        String NKS = txtB1R1.getText()+txtB1R3.getText()+txtB1R4.getText()+txtB1R5.getText()+
                txtB1R7.getText();
        return NKS;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new pkl49.component.PanelGradient();
        noUrutSAmpel = new pkl49.component.PanelTransparan();
        txtB1R7 = new pkl49.component.TextField();
        label8 = new pkl49.component.Label();
        label29 = new pkl49.component.Label();
        noBS = new pkl49.component.PanelTransparan();
        label5 = new pkl49.component.Label();
        txtB1R5 = new pkl49.component.TextField();
        Desa = new pkl49.component.PanelTransparan();
        txtB1R4 = new pkl49.component.TextField();
        label4 = new pkl49.component.Label();
        kecamatan = new pkl49.component.PanelTransparan();
        txtB1R3 = new pkl49.component.TextField();
        label3 = new pkl49.component.Label();
        kabupaten = new pkl49.component.PanelTransparan();
        label2 = new pkl49.component.Label();
        txtB1R1 = new pkl49.component.TextField();
        btnOK = new pkl49.component.ButtonGloss();
        btnCancel = new pkl49.component.ButtonGloss();
        label9 = new pkl49.component.Label();

        setLayout(new java.awt.BorderLayout());

        panelGradient1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelGradient1.setFirstColor(new java.awt.Color(0, 51, 255));
        panelGradient1.setSecondColor(new java.awt.Color(153, 255, 255));

        noUrutSAmpel.setBorder(null);

        txtB1R7.setLength(2);

        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("No. Urut Rumah"); // NOI18N

        label29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label29.setText("Tangga Sampel"); // NOI18N

        javax.swing.GroupLayout noUrutSAmpelLayout = new javax.swing.GroupLayout(noUrutSAmpel);
        noUrutSAmpel.setLayout(noUrutSAmpelLayout);
        noUrutSAmpelLayout.setHorizontalGroup(
            noUrutSAmpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
            .addComponent(label29, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noUrutSAmpelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtB1R7, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        noUrutSAmpelLayout.setVerticalGroup(
            noUrutSAmpelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noUrutSAmpelLayout.createSequentialGroup()
                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(label29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(txtB1R7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        noBS.setBorder(null);

        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("No. Blok sensus"); // NOI18N

        txtB1R5.setCharType(1);
        txtB1R5.setLength(4);

        javax.swing.GroupLayout noBSLayout = new javax.swing.GroupLayout(noBS);
        noBS.setLayout(noBSLayout);
        noBSLayout.setHorizontalGroup(
            noBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtB1R5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        noBSLayout.setVerticalGroup(
            noBSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noBSLayout.createSequentialGroup()
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtB1R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Desa.setBorder(null);

        txtB1R4.setLength(3);

        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Desa/Kel"); // NOI18N

        javax.swing.GroupLayout DesaLayout = new javax.swing.GroupLayout(Desa);
        Desa.setLayout(DesaLayout);
        DesaLayout.setHorizontalGroup(
            DesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtB1R4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        DesaLayout.setVerticalGroup(
            DesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesaLayout.createSequentialGroup()
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtB1R4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kecamatan.setBorder(null);

        txtB1R3.setColumns(3);
        txtB1R3.setLength(3);

        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Kecamatan"); // NOI18N

        javax.swing.GroupLayout kecamatanLayout = new javax.swing.GroupLayout(kecamatan);
        kecamatan.setLayout(kecamatanLayout);
        kecamatanLayout.setHorizontalGroup(
            kecamatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtB1R3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        kecamatanLayout.setVerticalGroup(
            kecamatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kecamatanLayout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtB1R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kabupaten.setBorder(null);

        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Kab/Kota"); // NOI18N

        txtB1R1.setLength(2);

        javax.swing.GroupLayout kabupatenLayout = new javax.swing.GroupLayout(kabupaten);
        kabupaten.setLayout(kabupatenLayout);
        kabupatenLayout.setHorizontalGroup(
            kabupatenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtB1R1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        kabupatenLayout.setVerticalGroup(
            kabupatenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kabupatenLayout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtB1R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnOK.setText("OK"); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel"); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setText("Masukkan Nomor Kode Sampel"); // NOI18N
        label9.setFont(new java.awt.Font("Tahoma", 1, 14));

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addComponent(kabupaten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(kecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(Desa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(noBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(noUrutSAmpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))))
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        panelGradient1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancel, btnOK});

        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kabupaten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Desa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(noBS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(noUrutSAmpel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelGradient1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancel, btnOK});

        add(panelGradient1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
       Controller.setForm(kues, this);
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       getParent().setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed


    private void control(KeyEvent e){
        if(e.getComponent().equals(txtB1R1)){
            if(e.getKeyChar()>=txtB1R1.getMinDigit() && e.getKeyChar()<=txtB1R1.getMaxDigit() && txtB1R1.getText().length()==txtB1R1.getLength()){
                txtB1R3.requestFocusInWindow();
            }
        }else if(e.getComponent().equals(txtB1R3)){
            if(e.getKeyChar()>=txtB1R3.getMinDigit() && e.getKeyChar()<=txtB1R3.getMaxDigit() && txtB1R3.getText().length()==txtB1R3.getLength()){
                txtB1R4.requestFocusInWindow();
            }
        }else if(e.getComponent().equals(txtB1R4)){
            if(e.getKeyChar()>=txtB1R4.getMinDigit() && e.getKeyChar()<=txtB1R4.getMaxDigit() && txtB1R4.getText().length()==txtB1R4.getLength()){
                txtB1R5.requestFocusInWindow();
            }
        }else if(e.getComponent().equals(txtB1R5) && !txtB1R5.getText().contains(" ")){
            if(e.getKeyChar()>=txtB1R5.getMinDigit() && e.getKeyChar()<=txtB1R5.getMaxDigit() && txtB1R5.getText().length()==txtB1R5.getLength()){
                txtB1R7.requestFocusInWindow();
            }
        }else if(e.getComponent().equals(txtB1R7)){
            if(e.getKeyChar()>=txtB1R7.getMinDigit() && e.getKeyChar()<=txtB1R7.getMaxDigit() && txtB1R7.getText().length()==txtB1R7.getLength()){
                getBtnOK().requestFocusInWindow();
            }
        }

    }

    public void showPanel(Component panel, String nama){
        if (panel.isVisible()){
            return;
        }
        ((CardLayout)formUtama.getPanelInduk().getLayout()).show(formUtama.getPanelInduk(), nama);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.PanelTransparan Desa;
    private pkl49.component.ButtonGloss btnCancel;
    private pkl49.component.ButtonGloss btnOK;
    private pkl49.component.PanelTransparan kabupaten;
    private pkl49.component.PanelTransparan kecamatan;
    private pkl49.component.Label label2;
    private pkl49.component.Label label29;
    private pkl49.component.Label label3;
    private pkl49.component.Label label4;
    private pkl49.component.Label label5;
    private pkl49.component.Label label8;
    private pkl49.component.Label label9;
    private pkl49.component.PanelTransparan noBS;
    private pkl49.component.PanelTransparan noUrutSAmpel;
    private pkl49.component.PanelGradient panelGradient1;
    private pkl49.component.TextField txtB1R1;
    private pkl49.component.TextField txtB1R3;
    private pkl49.component.TextField txtB1R4;
    private pkl49.component.TextField txtB1R5;
    private pkl49.component.TextField txtB1R7;
    // End of variables declaration//GEN-END:variables

    public void keyTyped(KeyEvent e) {
        
    }

    public void keyPressed(KeyEvent e) {
        
    }

    public void keyReleased(KeyEvent e) {
        control(e);
    }

}
