/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelInputNKD.java
 *
 * Created on Feb 12, 2010, 5:24:07 AM
 */

package pkl49.view;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import javax.swing.JOptionPane;
import pkl49.component.ButtonGloss;
import pkl49.component.TextField;
import pkl49.control.Controller;

/**
 *
 * @author Ade KeciL
 */
public class PanelInputNKD extends javax.swing.JPanel implements KeyListener{

    private PanelKuesionerPodes kues;
    private FormUtama formUtama;
    /** Creates new form PanelInputNKD */
    public PanelInputNKD() {
        initComponents();
        setOpaque(false);
        txtB1R1.addKeyListener(this);
        txtB1R2.addKeyListener(this);
        txtB1R3.addKeyListener(this);
        txtB1R4.addKeyListener(this);
        addMouseListener(new MouseListener() {

            public void mouseClicked(MouseEvent e) {

            }

            public void mousePressed(MouseEvent e) {

            }

            public void mouseReleased(MouseEvent e) {

            }

            public void mouseEntered(MouseEvent e) {

            }

            public void mouseExited(MouseEvent e) {

            }
        });
    }

    public TextField getTxtB1R1() {
        return txtB1R1;
    }



    public PanelKuesionerPodes getKues() {
        return kues;
    }

    public FormUtama getFormUtama() {
        return formUtama;
    }

    public void setKues(PanelKuesionerPodes kues) {
        this.kues = kues;
    }

    public void setFormUtama(FormUtama formUtama) {
        this.formUtama = formUtama;
    }



    public ButtonGloss getBtnCancel() {
        return btnCancel;
    }

    public ButtonGloss getBtnOK() {
        return btnOK;
    }

    public String getNKD(){
        String NKD = txtB1R1.getText()+txtB1R3.getText()+txtB1R4.getText();
        return NKD;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new pkl49.component.PanelGradient();
        Desa = new pkl49.component.PanelTransparan();
        txtB1R4 = new pkl49.component.TextField();
        label4 = new pkl49.component.Label();
        kecamatan = new pkl49.component.PanelTransparan();
        txtB1R3 = new pkl49.component.TextField();
        label3 = new pkl49.component.Label();
        kabupaten = new pkl49.component.PanelTransparan();
        label2 = new pkl49.component.Label();
        txtB1R1 = new pkl49.component.TextField();
        btnOK = new pkl49.component.ButtonGloss();
        btnCancel = new pkl49.component.ButtonGloss();
        label9 = new pkl49.component.Label();
        statifikasi = new pkl49.component.PanelTransparan();
        txtB1R2 = new pkl49.component.TextField();
        label28 = new pkl49.component.Label();
        label30 = new pkl49.component.Label();

        setLayout(new java.awt.GridBagLayout());

        panelGradient1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        panelGradient1.setFirstColor(new java.awt.Color(0, 53, 255));
        panelGradient1.setSecondColor(new java.awt.Color(102, 255, 255));

        Desa.setBorder(null);

        txtB1R4.setLength(3);

        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("Desa/Kel"); // NOI18N

        javax.swing.GroupLayout DesaLayout = new javax.swing.GroupLayout(Desa);
        Desa.setLayout(DesaLayout);
        DesaLayout.setHorizontalGroup(
            DesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesaLayout.createSequentialGroup()
                .addGroup(DesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtB1R4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        DesaLayout.setVerticalGroup(
            DesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesaLayout.createSequentialGroup()
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtB1R4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kecamatan.setBorder(null);

        txtB1R3.setColumns(3);
        txtB1R3.setLength(3);

        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("Kecamatan"); // NOI18N

        javax.swing.GroupLayout kecamatanLayout = new javax.swing.GroupLayout(kecamatan);
        kecamatan.setLayout(kecamatanLayout);
        kecamatanLayout.setHorizontalGroup(
            kecamatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtB1R3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        kecamatanLayout.setVerticalGroup(
            kecamatanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kecamatanLayout.createSequentialGroup()
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtB1R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        kabupaten.setBorder(null);

        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("Kab/Kota"); // NOI18N

        txtB1R1.setLength(2);

        javax.swing.GroupLayout kabupatenLayout = new javax.swing.GroupLayout(kabupaten);
        kabupaten.setLayout(kabupatenLayout);
        kabupatenLayout.setHorizontalGroup(
            kabupatenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtB1R1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        kabupatenLayout.setVerticalGroup(
            kabupatenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kabupatenLayout.createSequentialGroup()
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txtB1R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setText("Masukkan Nomor Kode Sampel Desa"); // NOI18N
        label9.setFont(new java.awt.Font("Tahoma", 1, 14));

        statifikasi.setBorder(null);

        txtB1R2.setMaxDigit('3');
        txtB1R2.setMinDigit('1');

        label28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label28.setText("Klasifikasi"); // NOI18N

        label30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label30.setText("Strata"); // NOI18N

        javax.swing.GroupLayout statifikasiLayout = new javax.swing.GroupLayout(statifikasi);
        statifikasi.setLayout(statifikasiLayout);
        statifikasiLayout.setHorizontalGroup(
            statifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label30, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(label28, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statifikasiLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(txtB1R2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        statifikasiLayout.setVerticalGroup(
            statifikasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statifikasiLayout.createSequentialGroup()
                .addComponent(label28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(label30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(txtB1R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addGroup(panelGradient1Layout.createSequentialGroup()
                        .addComponent(kabupaten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelGradient1Layout.createSequentialGroup()
                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelGradient1Layout.createSequentialGroup()
                                .addComponent(statifikasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(Desa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Desa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kabupaten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statifikasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kecamatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addGroup(panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(panelGradient1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        Controller.setFormPodes(kues, this);
}//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D gd = (Graphics2D) g.create();
        int w = getWidth();
        int h = getHeight();
        gd.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        gd.setColor(new Color(1f, 1f, 1f, 0.5f));
        gd.fillRect(0, 0, w, h);
        gd.dispose();
    }

    private void control(KeyEvent e){
        if(e.getComponent().equals(txtB1R1)){
            if(e.getKeyChar()>=txtB1R1.getMinDigit() && e.getKeyChar()<=txtB1R1.getMaxDigit() && txtB1R1.getText().length()==txtB1R1.getLength()){
                txtB1R2.requestFocusInWindow();
            }
        }else if(e.getComponent().equals(txtB1R2)){
            if(e.getKeyChar()>=txtB1R2.getMinDigit() && e.getKeyChar()<=txtB1R2.getMaxDigit() && txtB1R2.getText().length()==txtB1R2.getLength()){
                txtB1R3.requestFocusInWindow();
            }
        }else if(e.getComponent().equals(txtB1R3)){
            if(e.getKeyChar()>=txtB1R3.getMinDigit() && e.getKeyChar()<=txtB1R3.getMaxDigit() && txtB1R3.getText().length()==txtB1R3.getLength()){
                txtB1R4.requestFocusInWindow();
            }
        }else if(e.getComponent().equals(txtB1R4)){
            if(e.getKeyChar()>=txtB1R4.getMinDigit() && e.getKeyChar()<=txtB1R4.getMaxDigit() && txtB1R4.getText().length()==txtB1R4.getLength()){
                getBtnOK().requestFocusInWindow();
            }
        }

    }

    protected  void showPanel(Component panel, String nama){
        if (panel.isVisible()){
            return;
        }
        ((CardLayout)formUtama.getPanelGradient1().getLayout()).show(formUtama.getPanelGradient1(), nama);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.PanelTransparan Desa;
    private pkl49.component.ButtonGloss btnCancel;
    private pkl49.component.ButtonGloss btnOK;
    private pkl49.component.PanelTransparan kabupaten;
    private pkl49.component.PanelTransparan kecamatan;
    private pkl49.component.Label label2;
    private pkl49.component.Label label28;
    private pkl49.component.Label label3;
    private pkl49.component.Label label30;
    private pkl49.component.Label label4;
    private pkl49.component.Label label9;
    private pkl49.component.PanelGradient panelGradient1;
    private pkl49.component.PanelTransparan statifikasi;
    private pkl49.component.TextField txtB1R1;
    private pkl49.component.TextField txtB1R2;
    private pkl49.component.TextField txtB1R3;
    private pkl49.component.TextField txtB1R4;
    // End of variables declaration//GEN-END:variables

    public void keyTyped(KeyEvent e) {
        
    }

    public void keyPressed(KeyEvent e) {
        
    }

    public void keyReleased(KeyEvent e) {
        control(e);
    }

}
