/*
 * Dilarang mengopi
 * Copyright 2010
 */

/*
 * Test.java
 *
 * Created on 21 Mar 10, 21:16:56
 */

package pkl49.view;

import com.sun.awt.AWTUtilities;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import pkl49.component.GlassPane;

/**
 *
 * @author Ken
 */
public class Test extends javax.swing.JFrame implements TimingTarget{

    Form form;
    GlassPane glassPane;
    Animator animator;
    float alpha;
    /** Creates new form Test */
    public Test() {
        initComponents();
        animator = new Animator(2000, this);
        animator.setDeceleration(.4f);
        animator.setAcceleration(0.2f);
        setTransparan(0f);
        

    }

    public void setAlpha(float alpha) {
        this.alpha = alpha;
    }

    public float getAlpha() {
        return alpha;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradient1 = new pkl49.component.PanelGradient();
        buttonGlass1 = new pkl49.component.ButtonGlass();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGlass1.setText("buttonGlass1");
        buttonGlass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGradient1Layout = new javax.swing.GroupLayout(panelGradient1);
        panelGradient1.setLayout(panelGradient1Layout);
        panelGradient1Layout.setHorizontalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(buttonGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        panelGradient1Layout.setVerticalGroup(
            panelGradient1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradient1Layout.createSequentialGroup()
                .addContainerGap(366, Short.MAX_VALUE)
                .addComponent(buttonGlass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(panelGradient1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGlass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass1ActionPerformed
        glassPane = new GlassPane();
        form = new Form();
        setGlassPane(glassPane);
        getGlassPane().setVisible(true);
        glassPane.showComponent(form);
    }//GEN-LAST:event_buttonGlass1ActionPerformed

    public void setTransparan(float a){
        if(AWTUtilities.isTranslucencySupported(AWTUtilities.Translucency.TRANSLUCENT)){
            AWTUtilities.setWindowOpacity(this, a);
        }
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);
        animator.start();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pkl49.component.ButtonGlass buttonGlass1;
    private pkl49.component.PanelGradient panelGradient1;
    // End of variables declaration//GEN-END:variables

    public void timingEvent(float fraction) {
        setAlpha(fraction);
        setTransparan(getAlpha());
    }

    public void begin() {

    }

    public void end() {

    }

    public void repeat() {

    }


}
